import { db, auth } from "../firebase-config.js";
import { collection, getDocs, deleteDoc, doc, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";

const COLLECTIONS=["payments","expenses"];
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
let userAktif=null;
function toast(msg){alert(msg)}
function injectStyle(){if(document.getElementById("ckKelolaDataStyle"))return;const s=document.createElement("style");s.id="ckKelolaDataStyle";s.textContent=`#panelKelolaData{border-radius:9px!important;margin-bottom:7px!important;box-shadow:0 1px 5px rgba(0,0,0,.035)!important}#panelKelolaData .card-body{padding:6px!important}#panelKelolaData .small{font-size:.58rem!important;line-height:1.15}#panelKelolaData strong{font-size:.7rem}#panelKelolaData .btn{font-size:.56rem!important;padding:2px 5px!important;border-radius:6px!important}#hasilKelolaData{margin-top:5px!important}#hasilKelolaData .alert{padding:4px 6px!important;font-size:.58rem!important;margin-bottom:4px!important}#hasilKelolaData .ck-clean-list{max-height:150px!important;overflow:auto;border-radius:6px!important}#hasilKelolaData .ck-clean-row{padding:3px 4px!important;gap:4px!important}#hasilKelolaData .ck-clean-row .small{font-size:.55rem!important}#hasilKelolaData .ck-clean-row .btn{flex:0 0 auto}`;document.head.appendChild(s)}
function buatPanel(){if(document.getElementById("panelKelolaData"))return;injectStyle();const anchor=document.querySelector(".mobile-container")||document.body;const panel=document.createElement("div");panel.id="panelKelolaData";panel.className="card custom-card mb-2";panel.innerHTML=`<div class="card-body"><div class="d-flex align-items-center justify-content-between gap-1"><div><strong><i class="bi bi-database-check text-success"></i> Kelola Data</strong><div class="small text-muted">Data lama dapat diperiksa dan dihapus di sini.</div></div><button id="btnTampilkanSemuaData" class="btn btn-outline-success btn-sm">Periksa</button></div><div id="hasilKelolaData"></div></div>`;const riwayat=document.querySelector("#daftarPembayaran,#daftarPengeluaran");if(riwayat?.closest(".card"))riwayat.closest(".card").before(panel);else anchor.prepend(panel);document.getElementById("btnTampilkanSemuaData")?.addEventListener("click",tampilkanSemuaData)}
async function bacaSemua(){if(!userAktif)throw new Error("Belum login.");const hasil={payments:[],expenses:[]};for(const name of COLLECTIONS){const snap=await getDocs(query(collection(db,name),where("uid","==",userAktif.uid)));hasil[name]=snap.docs.map(d=>({id:d.id,...d.data()}))}return hasil}
function label(x,type){return type==="payments"?`${x.tanggal||"-"} · ${x.nama||x.namaSantri||x.keterangan||"-"} · ${x.jenis||x.kategori||"Lainnya"}`:`${x.tanggal||"-"} · ${x.keterangan||x.nama||x.deskripsi||"-"} · ${x.jenis||x.kategori||"Lainnya"}`}
async function tampilkanSemuaData(){const out=document.getElementById("hasilKelolaData"),btn=document.getElementById("btnTampilkanSemuaData");if(!out)return;try{if(btn){btn.disabled=true;btn.textContent="..."}const data=await bacaSemua(),total=data.payments.length+data.expenses.length;out.innerHTML=`<div class="alert alert-light border"><strong>${total}</strong> transaksi · ${data.payments.length} pemasukan · ${data.expenses.length} pengeluaran</div>`;const list=[...data.payments.map(x=>({...x,_type:"payments"})),...data.expenses.map(x=>({...x,_type:"expenses"}))];if(list.length){const box=document.createElement("div");box.className="border rounded ck-clean-list";list.slice().reverse().forEach(x=>{const row=document.createElement("div");row.className="d-flex align-items-center justify-content-between border-bottom ck-clean-row";row.innerHTML=`<span class="small">${esc(x._type==="payments"?"Pemasukan":"Pengeluaran")}: ${esc(label(x,x._type))}</span><button class="btn btn-outline-danger btn-sm" data-clean-one="${esc(x.id)}" data-clean-type="${esc(x._type)}">Hapus</button>`;box.appendChild(row)});out.appendChild(box);const all=document.createElement("button");all.className="btn btn-danger btn-sm mt-1";all.textContent="Hapus Semua";all.addEventListener("click",hapusSemua);out.appendChild(all)}else out.insertAdjacentHTML("beforeend",'<div class="small text-muted py-1">Tidak ada transaksi.</div>');out.querySelectorAll("[data-clean-one]").forEach(b=>b.addEventListener("click",async()=>{await hapusSatu(b.dataset.cleanType,b.dataset.cleanOne);await tampilkanSemuaData()}))}catch(e){out.innerHTML=`<div class="alert alert-danger">Gagal membaca data: ${esc(e.message||e)}</div>`}finally{if(btn){btn.disabled=false;btn.textContent="Periksa"}}}
async function hapusSatu(type,id){if(!userAktif||!COLLECTIONS.includes(type)||!id)return;if(!confirm("Hapus transaksi ini secara permanen?"))return;await deleteDoc(doc(db,type,id));localStorage.setItem("catatanKasDataBerubah",String(Date.now()));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"))}
async function hapusSemua(){if(!userAktif)return;const data=await bacaSemua(),total=data.payments.length+data.expenses.length;if(!total)return toast("Tidak ada transaksi untuk dihapus.");if(!confirm(`Anda akan menghapus ${total} transaksi dari akun ini. Lanjutkan?`))return;if(!confirm("PERINGATAN: semua pembayaran dan pengeluaran akun ini akan dihapus permanen. Pengaturan dan data santri tidak ikut dihapus. Lanjutkan?"))return;for(const type of COLLECTIONS)for(const x of data[type])await deleteDoc(doc(db,type,x.id));localStorage.setItem("catatanKasDataBerubah",String(Date.now()));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"));toast(`Berhasil menghapus ${total} transaksi.`);await tampilkanSemuaData()}
onAuthStateChanged(auth,u=>{userAktif=u||null;if(userAktif){if(document.readyState!=="loading")buatPanel()}});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",buatPanel);else buatPanel();
