// ======================================
// PENGATURAN APLIKASI - JS
// ======================================
const PENGATURAN_DEFAULT={namaPondok:"",subJudul:"",mataUang:"Rupiah",tema:"light"};
const LOGO_DEFAULT="logo-catatan-kas.jpg";
const SETTINGS_KEY="pengaturanAplikasi";
const LOGO_KEY="logoDashboard";
const PENDING_KEY="pengaturanAplikasiPending";
function uid(){return String(window.currentFirebaseUid||window.currentFirebaseUser?.uid||"").trim()}
function scoped(key){const u=uid();return u?`${key}_${u}`:key}
function getItem(key){try{return localStorage.getItem(scoped(key))}catch(_){return null}}
function setItem(key,value){try{localStorage.setItem(scoped(key),value)}catch(_){}}
function removeItem(key){try{localStorage.removeItem(scoped(key))}catch(_){} }
function bacaPengaturan(){try{const raw=getItem(SETTINGS_KEY);return{...PENGATURAN_DEFAULT,...(raw?JSON.parse(raw):{})};}catch(_){return{...PENGATURAN_DEFAULT};}}
function samaPengaturan(a,b){return JSON.stringify({...PENGATURAN_DEFAULT,...a})===JSON.stringify({...PENGATURAN_DEFAULT,...b});}
function tandaiPending(data){try{setItem(PENDING_KEY,JSON.stringify({data:{...PENGATURAN_DEFAULT,...data},savedAt:Date.now()}));}catch(_) {}}
function cekPendingSetelahCloud(){try{const raw=getItem(PENDING_KEY);if(!raw)return;const pending=JSON.parse(raw)?.data;if(!pending)return;const current=bacaPengaturan();if(samaPengaturan(current,pending)){removeItem(PENDING_KEY);return;}setItem(SETTINGS_KEY,JSON.stringify(pending));terapkanTema(pending.tema);window.dispatchEvent(new CustomEvent("settingsChanged",{detail:{...pending,restoredAfterCloud:true}}));muatFormPengaturan();}catch(_) {}}
function simpanDataPengaturan(data){const value={...PENGATURAN_DEFAULT,...data};setItem(SETTINGS_KEY,JSON.stringify(value));tandaiPending(value);window.dispatchEvent(new CustomEvent("settingsChanged",{detail:{...value}}));}
function terapkanTema(tema){let dark=tema==="dark";if(tema==="system")dark=window.matchMedia?.("(prefers-color-scheme: dark)")?.matches===true;document.documentElement.classList.toggle("dark-mode",dark);document.body?.classList.toggle("dark-mode",dark);}
function logoTersimpan(){try{return getItem(LOGO_KEY)||LOGO_DEFAULT;}catch(_){return LOGO_DEFAULT;}}
function tampilkanLogo(){const logo=logoTersimpan();document.querySelectorAll("#previewLogoDashboard,#logoPreviewV2,#logoPreview,#logoDashboard,.app-logo,.ck-logo,#dashboardLogo,#logo,#laporanLogo,[data-dashboard-logo]").forEach(el=>{if(el?.tagName==="IMG"){el.src=logo;el.removeAttribute("srcset");el.removeAttribute("data-src");}});window.dispatchEvent(new CustomEvent("logoDashboardChanged",{detail:{logo}}));}
function kompresLogo(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("File gambar tidak dapat dibaca."));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("File bukan gambar yang valid."));img.onload=()=>{const max=512,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");if(!ctx)return reject(new Error("Perangkat tidak mendukung pemrosesan gambar."));ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82));};img.src=reader.result;};reader.readAsDataURL(file);});}
async function simpanLogo(file){if(!file)return;if(!file.type?.startsWith("image/"))throw new Error("Silakan pilih file gambar.");if(file.size>10*1024*1024)throw new Error("Ukuran file terlalu besar. Maksimal 10 MB.");const data=await kompresLogo(file);try{setItem(LOGO_KEY,data);}catch(_){throw new Error("Logo tidak dapat disimpan. Penyimpanan mungkin penuh.");}tampilkanLogo();}
function resetLogo(){removeItem(LOGO_KEY);tampilkanLogo();}
function muatFormPengaturan(){const d=bacaPengaturan();const n=document.getElementById("namaPondok"),s=document.getElementById("subJudul"),m=document.getElementById("mataUang"),t=document.getElementById("tema");if(n)n.value=d.namaPondok||"";if(s)s.value=d.subJudul||"";if(m)m.value=d.mataUang||"Rupiah";if(t)t.value=d.tema||"light";terapkanTema(d.tema);tampilkanLogo();}
async function simpanPengaturan(){const btn=document.getElementById("simpanPengaturanButton"),spinner=document.getElementById("loadingSpinner"),txt=document.getElementById("btnText"),data={namaPondok:document.getElementById("namaPondok")?.value.trim()||"",subJudul:document.getElementById("subJudul")?.value.trim()||"",mataUang:document.getElementById("mataUang")?.value||"Rupiah",tema:document.getElementById("tema")?.value||"light"};if(!data.namaPondok)return alert("Nama lembaga belum diisi.");btn&&(btn.disabled=true);spinner?.classList.remove("d-none");if(txt)txt.innerHTML=" Menyimpan...";try{simpanDataPengaturan(data);terapkanTema(data.tema);const file=document.getElementById("logoDashboardInput")?.files?.[0];if(file)await simpanLogo(file);alert("✅ Pengaturan lembaga berhasil disimpan!");}catch(e){alert("❌ "+e.message);}finally{btn&&(btn.disabled=false);spinner?.classList.add("d-none");if(txt)txt.innerHTML='<i class="bi bi-save"></i> Simpan Pengaturan';}}
function resetSemuaPengaturan(){if(!confirm("Kembalikan pengaturan awal? Data transaksi tidak akan dihapus."))return;simpanDataPengaturan(PENGATURAN_DEFAULT);resetLogo();muatFormPengaturan();}
function muatPengelolaJenis(){if(!location.pathname.endsWith("pengaturan.html")||document.getElementById("ckJenisKeuanganLoader"))return;const s=document.createElement("script");s.id="ckJenisKeuanganLoader";s.src="js/jenis-keuangan.js";document.body.appendChild(s);}
window.CatatanKasSettings={get:bacaPengaturan,getLogo:logoTersimpan,applyTheme:terapkanTema,applyLogo:tampilkanLogo};
document.addEventListener("DOMContentLoaded",()=>{muatFormPengaturan();cekPendingSetelahCloud();document.getElementById("simpanPengaturanButton")?.addEventListener("click",simpanPengaturan);document.getElementById("resetPengaturanButton")?.addEventListener("click",resetSemuaPengaturan);document.getElementById("resetLogoButton")?.addEventListener("click",()=>{resetLogo();const i=document.getElementById("logoDashboardInput");if(i)i.value="";alert("✅ Logo bawaan digunakan kembali.");});document.getElementById("logoDashboardInput")?.addEventListener("change",async e=>{try{await simpanLogo(e.target.files?.[0]);alert("✅ Logo berhasil disimpan.");}catch(err){e.target.value="";alert("❌ "+err.message);}});document.getElementById("tema")?.addEventListener("change",e=>terapkanTema(e.target.value));muatPengelolaJenis();});
window.addEventListener("accountDataReady",()=>{setTimeout(cekPendingSetelahCloud,50);setTimeout(cekPendingSetelahCloud,500);});
window.addEventListener("storage",e=>{if(e.key===LOGO_KEY)tampilkanLogo();if(e.key===SETTINGS_KEY)terapkanTema(bacaPengaturan().tema);});