import { db, auth } from "../firebase-config.js";
import { doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
const $=id=>document.getElementById(id);let uid='';let loading=false;
const defaultSettings={namaPondok:'',subJudul:'',mataUang:'Rupiah',tema:'system'};
const storageKey=()=>uid?`pengaturanAplikasi_${uid}`:'pengaturanAplikasi';
const logoKey=()=>uid?`logoDashboard_${uid}`:'logoDashboard';
function readLocal(){try{return JSON.parse(localStorage.getItem(storageKey())||'{}')||{}}catch(_){return{}}}
function writeLocal(data){try{localStorage.setItem(storageKey(),JSON.stringify(data))}catch(_){} }
function setStatus(message,error=false){const e=$('statusPengaturan');if(e){e.textContent=message;e.classList.toggle('text-danger',error);e.classList.toggle('text-success',!error)}}
function applyTheme(value,save=true){const t=['light','dark','system'].includes(value)?value:'system';if(window.themeManager?.setTheme){window.themeManager.setTheme(t,save);return}const resolved=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;document.documentElement.classList.toggle('dark-mode',resolved==='dark');document.documentElement.classList.toggle('light-mode',resolved==='light');document.documentElement.setAttribute('data-theme',resolved);document.documentElement.style.colorScheme=resolved;try{localStorage.setItem(uid?`themeMode_${uid}`:'themeMode',t)}catch(_){} }
function fillForm(data){if($('namaPondok'))$('namaPondok').value=data.namaPondok||data.namaLembaga||data.namalembaga||'';if($('subJudul'))$('subJudul').value=data.subJudul||data.subjudul||'';if($('mataUang'))$('mataUang').value=data.mataUang||'Rupiah';if($('tema'))$('tema').value=['light','dark','system'].includes(data.tema)?data.tema:'system';const savedLogo=localStorage.getItem(logoKey())||data.logoDashboard||'logo-catatan-kas.jpg';if($('previewLogoDashboard'))$('previewLogoDashboard').src=savedLogo;applyTheme($('tema')?.value||'system',false)}
async function loadSettings(userUid){uid=userUid||'';let data={...defaultSettings,...readLocal()};if(uid){try{const snap=await getDoc(doc(db,'settings',uid));if(snap.exists())data={...data,...snap.data()}}catch(e){console.warn('Pengaturan Firestore tidak tersedia, memakai data lokal.',e)}}writeLocal(data);fillForm(data);window.dispatchEvent(new Event('settingsChanged'))}
async function saveSettings(){if(loading)return;const data={...readLocal(),namaPondok:$('namaPondok')?.value?.trim()||'',namaLembaga:$('namaPondok')?.value?.trim()||'',subJudul:$('subJudul')?.value?.trim()||'',mataUang:$('mataUang')?.value||'Rupiah',tema:$('tema')?.value||'system',updatedAt:new Date().toISOString()};writeLocal(data);applyTheme(data.tema,true);window.dispatchEvent(new Event('settingsChanged'));try{loading=true;if(uid)await setDoc(doc(db,'settings',uid),data,{merge:true});setStatus(uid?'Pengaturan tersimpan dan disinkronkan ke akun.':'Pengaturan tersimpan di perangkat.')}catch(e){console.error('Gagal menyimpan pengaturan:',e);setStatus('Pengaturan tersimpan di perangkat, tetapi gagal sinkron ke akun.',true)}finally{loading=false}}
function previewLogo(file){if(!file||!file.type.startsWith('image/'))return;const reader=new FileReader();reader.onload=async e=>{const src=e.target.result;if($('previewLogoDashboard'))$('previewLogoDashboard').src=src;try{localStorage.setItem(logoKey(),src)}catch(_){}if(uid){try{await setDoc(doc(db,'settings',uid),{logoDashboard:src,updatedAt:new Date().toISOString()},{merge:true});setStatus('Logo berhasil disimpan.')}catch(err){console.error('Gagal menyimpan logo ke akun:',err);setStatus('Logo tersimpan di perangkat, tetapi gagal sinkron ke akun.',true)}}else setStatus('Logo berhasil disimpan di perangkat.');window.dispatchEvent(new Event('logoDashboardChanged'));window.dispatchEvent(new Event('settingsChanged'))};reader.readAsDataURL(file)}
function resetLogo(){if($('previewLogoDashboard'))$('previewLogoDashboard').src='logo-catatan-kas.jpg';try{localStorage.removeItem(logoKey())}catch(_){}if(uid)setDoc(doc(db,'settings',uid),{logoDashboard:'logo-catatan-kas.jpg',updatedAt:new Date().toISOString()},{merge:true}).catch(e=>console.error('Gagal mereset logo:',e));window.dispatchEvent(new Event('logoDashboardChanged'));setStatus('Logo dikembalikan ke bawaan.')}
$('tema')?.addEventListener('change',()=>applyTheme($('tema').value,true));['namaPondok','subJudul','mataUang'].forEach(id=>$(id)?.addEventListener('change',saveSettings));$('simpanPengaturanButton')?.addEventListener('click',saveSettings);$('logoDashboardInput')?.addEventListener('change',e=>previewLogo(e.target.files?.[0]));$('resetLogoButton')?.addEventListener('click',resetLogo);$('resetPengaturanButton')?.addEventListener('click',async()=>{if(!confirm('Kembalikan pengaturan awal?'))return;const data={...defaultSettings,updatedAt:new Date().toISOString()};fillForm(data);writeLocal(data);applyTheme('system',true);if(uid)try{await setDoc(doc(db,'settings',uid),data,{merge:true})}catch(e){console.error(e)}setStatus('Pengaturan dikembalikan ke awal')});
onAuthStateChanged(auth,u=>{if(u){uid=u.uid;const email=$('emailAkun');if(email)email.textContent=u.email||'Akun aktif';loadSettings(u.uid)}else{uid='';const email=$('emailAkun');if(email)email.textContent='Belum login — mode umum';loadSettings('')}});
window.addEventListener('themeChanged',e=>{const t=e.detail?.theme||'system';if($('tema')&&$('tema').value!==t)$('tema').value=t});
