// Pengaturan account-scoped + cloud persistence
import { db, auth } from "../firebase-config.js";
import { doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";

const DEFAULT={namaPondok:"",subJudul:"",mataUang:"Rupiah",tema:"light"};
const SETTINGS="pengaturanAplikasi", LOGO="logoDashboard", PENDING="pengaturanAplikasiPending", DEFAULT_LOGO="logo-catatan-kas.jpg";
let activeUid="";
const uid=()=>String(activeUid||auth.currentUser?.uid||window.currentFirebaseUid||window.currentFirebaseUser?.uid||"").trim();
const key=k=>{const u=uid();return u?`${k}_${u}`:k};
const get=k=>{try{return localStorage.getItem(key(k))}catch(_){return null}};
const set=(k,v)=>{try{localStorage.setItem(key(k),v);return true}catch(_){return false}};
const remove=k=>{try{localStorage.removeItem(key(k))}catch(_) {}};
function read(){try{return {...DEFAULT,...JSON.parse(get(SETTINGS)||"{}")}}catch(_){return {...DEFAULT}}}
function logo(){return get(LOGO)||DEFAULT_LOGO}
function theme(v){let dark=v==="dark";if(v==="system")dark=window.matchMedia?.("(prefers-color-scheme: dark)")?.matches===true;document.documentElement.classList.toggle("dark-mode",dark);document.body?.classList.toggle("dark-mode",dark);document.documentElement.setAttribute("data-theme",dark?"dark":"light")}
function apply(){const d=read();theme(d.tema);showLogo();fill();window.dispatchEvent(new CustomEvent("settingsChanged",{detail:{...d,uid:uid()}}))}
function showLogo(){const src=logo();document.querySelectorAll("#previewLogoDashboard,#logoPreviewV2,#logoPreview,#logoDashboard,.app-logo,.ck-logo,#dashboardLogo,#logo,#laporanLogo,[data-dashboard-logo]").forEach(e=>{if(e?.tagName==="IMG"){e.src=src;e.removeAttribute("srcset")}});window.dispatchEvent(new CustomEvent("logoDashboardChanged",{detail:{logo:src,uid:uid()}}))}
function fill(){const d=read();const n=document.getElementById("namaPondok"),s=document.getElementById("subJudul"),m=document.getElementById("mataUang"),t=document.getElementById("tema");if(n)n.value=d.namaPondok||"";if(s)s.value=d.subJudul||"";if(m)m.value=d.mataUang||"Rupiah";if(t)t.value=d.tema||"light";theme(d.tema)}
async function cloud(data,logoValue){const u=uid();if(!u)return;try{await setDoc(doc(db,"users",u),{pengaturan:{...data,logoDashboard:logoValue||DEFAULT_LOGO},updatedAt:new Date().toISOString()},{merge:true});remove(PENDING)}catch(e){set(PENDING,JSON.stringify({...data,logoDashboard:logoValue||DEFAULT_LOGO}));console.warn("Pengaturan lokal; cloud gagal:",e)}}
async function load(user){activeUid=user.uid;window.currentFirebaseUid=user.uid;window.currentFirebaseUser=user;try{const snap=await getDoc(doc(db,"users",user.uid));if(snap.exists()){const p=snap.data()?.pengaturan;if(p&&typeof p==="object"){set(SETTINGS,JSON.stringify({...DEFAULT,p}));if(p.logoDashboard)set(LOGO,p.logoDashboard)}}}catch(e){console.warn("Gagal memuat pengaturan cloud",e)}apply();window.dispatchEvent(new CustomEvent("accountDataReady",{detail:{uid:user.uid}}))}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error("File gambar tidak dapat dibaca."));r.onload=()=>{const i=new Image();i.onerror=()=>reject(new Error("File gambar tidak valid."));i.onload=()=>{const max=512,sc=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(i.width*sc));c.height=Math.max(1,Math.round(i.height*sc));const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height);x.drawImage(i,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.82))};i.src=r.result};r.readAsDataURL(file)})}
async function saveLogo(file){if(!file)return;if(!file.type?.startsWith("image/"))throw new Error("Silakan pilih file gambar.");if(file.size>10*1024*1024)throw new Error("Ukuran file maksimal 10 MB.");const v=await compress(file);if(!set(LOGO,v))throw new Error("Penyimpanan logo penuh.");showLogo();await cloud(read(),v)}
async function saveSettings(){const btn=document.getElementById("simpanPengaturanButton"),data={namaPondok:document.getElementById("namaPondok")?.value.trim()||"",subJudul:document.getElementById("subJudul")?.value.trim()||"",mataUang:document.getElementById("mataUang")?.value||"Rupiah",tema:document.getElementById("tema")?.value||"light"};if(!data.namaPondok)return alert("Nama lembaga belum diisi.");if(btn)btn.disabled=true;try{set(SETTINGS,JSON.stringify(data));theme(data.tema);const f=document.getElementById("logoDashboardInput")?.files?.[0];if(f)await saveLogo(f);else await cloud(data,logo());apply();alert("✅ Pengaturan berhasil disimpan!")}catch(e){set(PENDING,JSON.stringify({...data,logoDashboard:logo()}));alert("❌ "+(e.message||e))}finally{if(btn)btn.disabled=false}}
async function resetLogo(){set(LOGO,DEFAULT_LOGO);showLogo();await cloud(read(),DEFAULT_LOGO)}
function resetAll(){if(!confirm("Kembalikan pengaturan awal? Data transaksi tidak dihapus."))return;set(SETTINGS,JSON.stringify(DEFAULT));resetLogo();apply()}
window.CatatanKasSettings={get:read,getLogo:logo,applyTheme:theme,applyLogo:showLogo,getUid:uid};
document.addEventListener("DOMContentLoaded",()=>{fill();document.getElementById("simpanPengaturanButton")?.addEventListener("click",saveSettings);document.getElementById("resetPengaturanButton")?.addEventListener("click",resetAll);document.getElementById("resetLogoButton")?.addEventListener("click",async()=>{await resetLogo();const i=document.getElementById("logoDashboardInput");if(i)i.value="";alert("✅ Logo bawaan digunakan kembali.")});document.getElementById("logoDashboardInput")?.addEventListener("change",async e=>{try{await saveLogo(e.target.files?.[0]);alert("✅ Logo berhasil disimpan.")}catch(err){e.target.value="";alert("❌ "+err.message)}});document.getElementById("tema")?.addEventListener("change",e=>theme(e.target.value))});
onAuthStateChanged(auth,u=>u?load(u):(activeUid="",apply()));
window.addEventListener("storage",e=>{if(e.key?.startsWith(LOGO))showLogo();if(e.key?.startsWith(SETTINGS))apply()});
