import { db, auth } from "../firebase-config.js";
import { collection, onSnapshot, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";

(()=>{
"use strict";
const MONTHS=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const amount=x=>Number(x?.nominal??x?.jumlah??x?.nilai??x?.total??0)||0;
const name=x=>String(x?.namaSantri??x?.nama_santri??x?.nama??x?.keterangan??"").trim();
const kind=x=>String(x?.jenis??x?.kategori??"Lainnya").trim()||"Lainnya";
function dateOf(x){const v=x?.tanggal??x?.createdAt;if(v?.toDate)return v.toDate();if(typeof v==="string"){const d=new Date(/^\d{4}-\d{2}-\d{2}$/.test(v)?v+"T00:00:00":v);if(!Number.isNaN(d.getTime()))return d}if(typeof v==="number"){const d=new Date(v);if(!Number.isNaN(d.getTime()))return d}return null}
function paidRange(x){let a=Number(x?.bulanDari??x?.bulanMulai??0)||0,b=Number(x?.bulanSampai??x?.bulanAkhir??0)||0;if(a&&b){if(a>b)[a,b]=[b,a];return[a,b]}if(a)return[a,a];const d=dateOf(x);return d?[d.getMonth()+1,d.getMonth()+1]:[]}
function settings(){try{const uid=auth.currentUser?.uid||"",keys=uid?[`pengaturanAplikasi_${uid}`,"pengaturanAplikasi"]:["pengaturanAplikasi"];for(const k of keys){const raw=localStorage.getItem(k);if(raw){const s=JSON.parse(raw)||{};if(s&&typeof s==="object")return s}}}catch(_){}return{}}
function theme(){const s=settings(),mode=String(s.tema??s.theme??s.mode??s.modeTema??"").toLowerCase(),dark=s.darkMode===true||mode==="dark"||mode==="gelap"||(mode==="system"&&window.matchMedia?.("(prefers-color-scheme: dark)").matches);document.documentElement.classList.toggle("dark-mode",dark);document.body.classList.toggle("dark-mode",dark)}
function styles(){if(document.getElementById("ckUiFixesStyle"))return;const s=document.createElement("style");s.id="ckUiFixesStyle";s.textContent=`#daftarPembayaran .ck-riwayat-actions,#daftarPengeluaran .ck-riwayat-actions{display:inline-flex!important;gap:3px!important;align-items:center!important;margin-left:5px!important}.ck-riwayat-actions button{width:24px!important;height:24px!important;padding:2px!important;font-size:.62rem!important;line-height:1!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;border-radius:6px!important;margin:0!important}#ckDaftarJenis .ck-setting-actions{display:inline-flex!important;gap:3px!important;align-items:center!important;margin-left:5px!important}.ck-setting-actions button{width:24px!important;height:24px!important;padding:2px!important;font-size:.62rem!important;line-height:1!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;border-radius:6px!important;margin:0!important}html.dark-mode body{background:#101514!important;color:#eef4f0!important}html.dark-mode .top,html.dark-mode .cardx,html.dark-mode .metric,html.dark-mode .bottom{background:#1b211f!important;color:#eef4f0!important;border-color:#34423b!important}html.dark-mode .sub,html.dark-mode .form-label,html.dark-mode .section,html.dark-mode .empty{color:#a7b2ac!important}html.dark-mode .form-control,html.dark-mode .form-select{background:#141a18!important;color:#eef4f0!important;border-color:#34423b!important}html.dark-mode .table{color:#eef4f0!important}html.dark-mode .table td{background:#1b211f!important;color:#eef4f0!important;border-color:#34423b!important}html.dark-mode .table th{background:#12382e!important;color:#fff!important}html.dark-mode .back,html.dark-mode .title{color:#73c99a!important}html.dark-mode .bottom a{color:#a7b2ac!important}html.dark-mode .bottom .active{color:#73c99a!important}.ck-dashboard-excel-fix .table td{font-size:.65rem!important}.ck-dashboard-excel-fix .table th{font-size:.62rem!important}`;document.head.appendChild(s)}
function settingsActions(){document.querySelectorAll("#ckDaftarJenis [data-edit-jenis],#ckDaftarJenis [data-hapus-jenis]").forEach(b=>{b.classList.add("btn","btn-sm");b.innerHTML=b.hasAttribute("data-edit-jenis")?"<i class='bi bi-pencil'></i>":"<i class='bi bi-trash'></i>";b.title=b.hasAttribute("data-edit-jenis")?"Edit":"Hapus"});}
function dashboardExcel(){if(!location.pathname.endsWith("dashboard-excel.html"))return;styles();document.documentElement.classList.add("ck-dashboard-excel-fix");theme();const cari=document.getElementById("cari"),tahun=document.getElementById("tahun"),jenis=document.getElementById("jenis"),body=document.getElementById("body");if(!cari||!tahun||!jenis||!body)return;let payments=[],santri=[],stop=[];const getTypes=()=>{try{const uid=auth.currentUser?.uid||"",raw=localStorage.getItem(uid?`jenisKeuanganCustom_${uid}`:"jenisKeuanganCustom")||"[]",arr=JSON.parse(raw);return Array.isArray(arr)?arr:[ ]}catch(_){return[]}};const fillTypes=()=>{const cur=jenis.value||"Semua",types=["Semua","SPP","Infaq","Kas",...getTypes(),"Lainnya"],seen=new Set();jenis.innerHTML=types.filter(x=>{const k=String(x).toLowerCase().trim();if(!k||seen.has(k)||k==="syahriyyah"||k==="beras")return false;seen.add(k);return true}).map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");jenis.value=[...jenis.options].some(o=>o.value.toLowerCase()===cur.toLowerCase())?cur:"Semua"};
const render=()=>{theme();fillTypes();const y=Number(tahun.value)||new Date().getFullYear(),t=jenis.value||"Semua",q=String(cari.value||"").toLowerCase().trim(),ps=payments.filter(x=>{const d=dateOf(x);return d&&d.getFullYear()===y&&(t==="Semua"||kind(x).toLowerCase()===t.toLowerCase())});const names=[...new Set([...santri,...payments].map(name).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"id"));const rows=names.filter(n=>!q||n.toLowerCase().includes(q)).map(n=>{const statuses=MONTHS.map((_,i)=>ps.some(x=>{if(name(x)!==n)return false;const r=paidRange(x);return r.length===2&&i+1>=r[0]&&i+1<=r[1]})),paid=statuses.filter(Boolean).length,total=ps.filter(x=>name(x)===n).reduce((sum,x)=>sum+amount(x),0);let last="Belum bayar";for(let i=11;i>=0;i--)if(statuses[i]){last=MONTHS[i];break}return{n,statuses,paid,total,last}});const totalAll=ps.reduce((s,x)=>s+amount(x),0);document.getElementById("mSantri")&&(document.getElementById("mSantri").textContent=names.length.toLocaleString("id-ID"));document.getElementById("mLengkap")&&(document.getElementById("mLengkap").textContent=rows.filter(x=>x.paid===12).length.toLocaleString("id-ID"));document.getElementById("mBelum")&&(document.getElementById("mBelum").textContent=rows.filter(x=>x.paid<12).length.toLocaleString("id-ID"));document.getElementById("mTotal")&&(document.getElementById("mTotal").textContent="Rp "+totalAll.toLocaleString("id-ID"));body.innerHTML=rows.length?rows.map(r=>`<tr><td><b>${esc(r.n)}</b></td>${r.statuses.map(v=>`<td class="${v?"ok":"no"}">${v?"✓":"✗"}</td>`).join("")}<td><b>${r.paid}/12</b></td><td class="last">${esc(r.last)}</td><td>Rp ${r.total.toLocaleString("id-ID")}</td></tr>`).join(""):"<tr><td colspan='16' class='empty'>Tidak ada data yang cocok.</td></tr>";const first=rows[0],detail=document.getElementById("detail");if(detail)detail.innerHTML=first?`<b>${esc(first.n)}</b><br>Sudah bayar sampai: <b class="last">${esc(first.last)}</b><br>Jumlah bulan: <b>${first.paid}/12</b>`:"Pilih/ketik nama pada kolom pencarian untuk melihat detail."};
[cari,tahun,jenis].forEach(e=>e?.addEventListener("input",render));[tahun,jenis].forEach(e=>e?.addEventListener("change",render));const start=u=>{stop.forEach(f=>f?.());stop=[];if(!u?.uid)return;stop.push(onSnapshot(query(collection(db,"payments"),where("uid","==",u.uid)),s=>{payments=s.docs.map(d=>({id:d.id,...d.data()}));fillTypes();render()}));stop.push(onSnapshot(query(collection(db,"santri"),where("uid","==",u.uid)),s=>{santri=s.docs.map(d=>({id:d.id,...d.data()}));render()}))};onAuthStateChanged(auth,start);window.addEventListener("settingsChanged",()=>{theme();render()});window.addEventListener("storage",e=>{if(e.key?.startsWith("pengaturanAplikasi")||e.key?.startsWith("jenisKeuanganCustom")){theme();fillTypes();render()}});window.addEventListener("jenisKeuanganBerubah",()=>{fillTypes();render()});setInterval(theme,800)}
function boot(){styles();settingsActions();dashboardExcel();setInterval(settingsActions,700)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();