import "./js/jenis-keuangan.js";
import { db, auth } from "./firebase-config.js";
import { collection, onSnapshot, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";

let semuaPembayaran=[],semuaPengeluaran=[],semuaSantri=[],userAktif=null;
let unsubscribePayments=null,unsubscribeExpenses=null,unsubscribeSantri=null;
let paymentsReady=false,expensesReady=false,santriReady=false;
const $=id=>document.getElementById(id);
const LOGO_DEFAULT="logo-catatan-kas.jpg";
function settings(){try{if(window.CatatanKasSettings?.get)return window.CatatanKasSettings.get();const u=userAktif?.uid;const k=u?`pengaturanAplikasi_${u}`:"pengaturanAplikasi";return JSON.parse(localStorage.getItem(k)||"{}")}catch(_){return {}}}
function lembagaAktif(){const s=settings();return String(s.namaPondok||s.namaLembaga||s.lembaga||"").trim()}
function logoDashboardTersimpan(){try{if(window.CatatanKasSettings?.getLogo)return window.CatatanKasSettings.getLogo();const u=userAktif?.uid;return localStorage.getItem(u?`logoDashboard_${u}`:"logoDashboard")||LOGO_DEFAULT}catch(_){return LOGO_DEFAULT}}
function terapkanIdentitasDashboard(){const s=settings(),nama=lembagaAktif(),title=nama||"Keuangan",subtitle=String(s.subJudul||s.subjudul||"").trim()||"Dashboard Keuangan";document.querySelectorAll(".app-name,[data-app-name]").forEach(e=>e.textContent=title);document.querySelectorAll(".app-subtitle,[data-app-subtitle]").forEach(e=>e.textContent=subtitle);document.title=nama?`${nama} | Keuangan`:"Keuangan | Dashboard"}
function muatLogoDashboard(){const logo=logoDashboardTersimpan();document.querySelectorAll(".app-logo,.ck-logo,#logoDashboard,#dashboardLogo,#logoPreviewV2,#logoPreview,#previewLogoDashboard,img[alt='Logo Dashboard'],img[alt='Logo aplikasi'],img[alt='Logo Catatan Kas'],[data-dashboard-logo]").forEach(e=>{if(e?.tagName==="IMG"){e.src=logo;e.removeAttribute("srcset");e.removeAttribute("data-src")}})}
function refreshLogoDanDashboard(){muatLogoDashboard();terapkanIdentitasDashboard();tampilkanDashboard()}
function rupiah(v){return "Rp"+(Number(v)||0).toLocaleString("id-ID")}
const ambilNominal=i=>Number(i?.nominal??i?.jumlah??i?.nilai??0)||0;
const ambilNominalPengeluaran=i=>Number(i?.nominal??i?.jumlah??i?.nilai??i?.harga??i?.total??0)||0;
const ambilKategoriPembayaran=i=>String(i?.jenis??i?.kategori??"").trim();
const ambilKategoriPengeluaran=i=>String(i?.jenis??i?.kategori??i?.keterangan??"").trim();
const ambilLembaga=i=>String(i?.lembagaNama??i?.lembaga??i?.namaLembaga??"").trim();
const cocok=(v,f)=>!f||f==="Semua"||String(v).trim().toLowerCase()===String(f).trim().toLowerCase();
function lembagaOptions(){const active=lembagaAktif(),list=[...new Set([...semuaPembayaran,...semuaPengeluaran].map(ambilLembaga).filter(Boolean))];if(active&&!list.some(x=>x.toLowerCase()===active.toLowerCase()))list.push(active);return list.sort((a,b)=>a.localeCompare(b,"id"))}
function pasangFilterLembaga(){let el=$("filterLembaga"),jenis=$("filterKategori");if(!jenis)return;if(!el){const wrap=document.createElement("div");wrap.id="filterLembagaWrap";wrap.className="mb-3";wrap.innerHTML='<label class="form-label fw-semibold" for="filterLembaga">Lembaga</label><select id="filterLembaga" class="form-select"><option value="Semua">Semua Lembaga</option></select>';const anchor=jenis.closest(".card")||jenis.parentElement;anchor?.parentElement?.insertBefore(wrap,anchor);el=wrap.querySelector("#filterLembaga");el.onchange=()=>tampilkanDashboard()}const current=el.value||"Semua",active=lembagaAktif();el.innerHTML='<option value="Semua">Semua Lembaga</option>';lembagaOptions().forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;el.appendChild(o)});if([...el.options].some(o=>o.value.toLowerCase()===current.toLowerCase()))el.value=current;else if(active&&[...el.options].some(o=>o.value.toLowerCase()===active.toLowerCase())&&current==="Semua")el.value=active;else el.value="Semua"}
function sinkronkanFilterKategori(){const el=$("filterKategori");if(el&&window.ckJenisKeuangan)window.ckJenisKeuangan.populate(el)}
function hitungDashboard(){const filter=$("filterKategori")?.value||"Semua",lembaga=$("filterLembaga")?.value||lembagaAktif()||"Semua",payments=semuaPembayaran.filter(i=>cocok(ambilLembaga(i),lembaga)),expenses=semuaPengeluaran.filter(i=>cocok(ambilLembaga(i),lembaga));const totalMasuk=payments.filter(i=>cocok(ambilKategoriPembayaran(i),filter)).reduce((s,i)=>s+ambilNominal(i),0),totalKeluar=expenses.filter(i=>cocok(ambilKategoriPengeluaran(i),filter)).reduce((s,i)=>s+ambilNominalPengeluaran(i),0);return{totalMasuk,totalKeluar,saldo:totalMasuk-totalKeluar,totalSantri:semuaSantri.length,filter,lembaga,uid:userAktif?.uid||null,loading:!(paymentsReady&&expensesReady&&santriReady)}}
function tampilkanDashboard(){sinkronkanFilterKategori();pasangFilterLembaga();const h=hitungDashboard();["totalMasuk","pemasukan","jumlahPemasukan"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.totalMasuk)});["totalKeluar","pengeluaran","jumlahPengeluaran"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.totalKeluar)});["totalSaldo","saldo","saldoSaatIni"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.saldo)});if($("totalSantri"))$("totalSantri").textContent=h.totalSantri.toLocaleString("id-ID");window.catatanKasDashboard=h}
function berhentiListener(){[unsubscribePayments,unsubscribeExpenses,unsubscribeSantri].forEach(fn=>{try{fn?.()}catch(_){}});unsubscribePayments=unsubscribeExpenses=unsubscribeSantri=null;paymentsReady=expensesReady=santriReady=false}
function mulaiPembayaran(){unsubscribePayments?.();if(!userAktif)return;unsubscribePayments=onSnapshot(query(collection(db,"payments"),where("uid","==",userAktif.uid)),s=>{semuaPembayaran=s.docs.map(d=>({id:d.id,...d.data()}));paymentsReady=true;tampilkanDashboard();window.dispatchEvent(new CustomEvent("dataKeuanganBerubah",{detail:{tipe:"pembayaran",uid:userAktif.uid}}))},e=>{console.error("Pembayaran Dashboard:",e);paymentsReady=false;window.dispatchEvent(new CustomEvent("dashboardDataError",{detail:{tipe:"pembayaran",uid:userAktif.uid,error:e}}));tampilkanDashboard()})}
function mulaiPengeluaran(){unsubscribeExpenses?.();if(!userAktif)return;unsubscribeExpenses=onSnapshot(query(collection(db,"expenses"),where("uid","==",userAktif.uid)),s=>{semuaPengeluaran=s.docs.map(d=>({id:d.id,...d.data()}));expensesReady=true;tampilkanDashboard();window.dispatchEvent(new CustomEvent("dataKeuanganBerubah",{detail:{tipe:"pengeluaran",uid:userAktif.uid}}))},e=>{console.error("Pengeluaran Dashboard:",e);expensesReady=false;window.dispatchEvent(new CustomEvent("dashboardDataError",{detail:{tipe:"pengeluaran",uid:userAktif.uid,error:e}}));tampilkanDashboard()})}
function mulaiSantri(){unsubscribeSantri?.();if(!userAktif)return;unsubscribeSantri=onSnapshot(query(collection(db,"santri"),where("uid","==",userAktif.uid)),s=>{semuaSantri=s.docs.map(d=>({id:d.id,...d.data(),source:"firestore"}));santriReady=true;tampilkanDashboard()},e=>{console.error("Santri Dashboard:",e);santriReady=false;window.dispatchEvent(new CustomEvent("dashboardDataError",{detail:{tipe:"santri",uid:userAktif.uid,error:e}}));tampilkanDashboard()})}
window.refreshDashboard=refreshLogoDanDashboard;window.addEventListener("dataKeuanganBerubah",()=>tampilkanDashboard());window.addEventListener("refreshDashboard",refreshLogoDanDashboard);window.addEventListener("logoDashboardChanged",muatLogoDashboard);window.addEventListener("settingsChanged",()=>{terapkanIdentitasDashboard();muatLogoDashboard();tampilkanDashboard()});
function pasangFilter(){const f=$("filterKategori");if(f)f.addEventListener("change",tampilkanDashboard)}
function pasangTombolDashboardExcel(){if(!document.body||$("btnDashboardExcelCatatanKas"))return;const menu=document.querySelector(".row.g-3.mb-4");if(!menu)return;const c=document.createElement("div");c.className="col-12";c.innerHTML='<a href="dashboard-excel.html" id="btnDashboardExcelCatatanKas" class="menu-btn"><i class="bi bi-file-earmark-spreadsheet"></i><h6>Dashboard Excel</h6><small>Rekap pembayaran perorang</small></a>';const p=menu.querySelector("a[href='pengaturan.html']")?.closest(".col-12");p?menu.insertBefore(c,p):menu.appendChild(c)}
function initApp(){pasangFilter();muatLogoDashboard();terapkanIdentitasDashboard();tampilkanDashboard();pasangTombolDashboardExcel()}
onAuthStateChanged(auth,u=>{berhentiListener();userAktif=u||null;semuaPembayaran=[];semuaPengeluaran=[];semuaSantri=[];if(userAktif){setTimeout(()=>{terapkanIdentitasDashboard();muatLogoDashboard();mulaiPembayaran();mulaiPengeluaran();mulaiSantri()},0)}tampilkanDashboard()});
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initApp);else initApp();