import "./js/jenis-keuangan.js";
import { db } from "./firebase-config.js";
import { collection, onSnapshot } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

let semuaPembayaran=[];let semuaPengeluaran=[];let semuaSantri=[];let unsubscribePayments=null,unsubscribeExpenses=null,unsubscribeSantri=null;
const $=id=>document.getElementById(id);const LOGO_DEFAULT="logo-catatan-kas.jpg";
function settings(){try{return JSON.parse(localStorage.getItem("pengaturanAplikasi")||"{}")}catch(_){return {}}}
function lembagaAktif(){return String(settings().namaPondok||"").trim()}
function logoDashboardTersimpan(){try{const s=settings(),saved=localStorage.getItem("logoDashboard");for(const c of [saved,s?.logoDashboard,s?.logo]){if(typeof c!=="string")continue;const l=c.trim();if(!l)continue;if(l==="assets/logo-catatan-kas.jpg"||l==="assets/logo-catatan-kas.png"||l==="logo-catatan-kas.png")continue;if(/^data:image\//i.test(l)||/^https?:\/\//i.test(l)||/^blob:/i.test(l)||/^(\.\/|\/)?[\w./-]+\.(jpe?g|png|webp|gif|svg)$/i.test(l))return l}return LOGO_DEFAULT}catch(_){return LOGO_DEFAULT}}
function muatLogoDashboard(){const logo=logoDashboardTersimpan();document.querySelectorAll([".app-logo",".ck-logo","#logoDashboard","#dashboardLogo","#logoPreviewV2","#logoPreview","#previewLogoDashboard","img[alt='Logo Dashboard']","img[alt='Logo aplikasi']","img[alt='Logo Catatan Kas']","[data-dashboard-logo]"].join(",")).forEach(e=>{if(e?.tagName==="IMG"){e.src=logo;e.removeAttribute("srcset");e.removeAttribute("data-src")}})}
function refreshLogoDanDashboard(){muatLogoDashboard();tampilkanDashboard()}
function rupiah(nilai){return "Rp"+(Number(nilai)||0).toLocaleString("id-ID")}
function ambilNominal(i){return Number(i?.nominal??i?.jumlah??i?.nilai??0)||0}
function ambilNominalPengeluaran(i){return Number(i?.nominal??i?.jumlah??i?.nilai??i?.harga??i?.total??0)||0}
function ambilKategoriPembayaran(i){return String(i?.jenis??i?.kategori??"").trim()}
function ambilKategoriPengeluaran(i){return String(i?.jenis??i?.kategori??i?.keterangan??"").trim()}
function ambilLembaga(i){return String(i?.lembagaNama??i?.lembaga??i?.namaLembaga??"").trim()}
function cocok(v,f){if(!f||f==="Semua")return true;return String(v).trim().toLowerCase()===String(f).trim().toLowerCase()}
function lembagaOptions(){return [...new Set([...semuaPembayaran,...semuaPengeluaran].map(ambilLembaga).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"id"))}
function pasangFilterLembaga(){let el=$("filterLembaga");const jenis=$("filterKategori");if(!el){const anchor=jenis?.parentElement;if(!anchor)return;el=document.createElement("select");el.id="filterLembaga";el.className="form-select mb-2";el.innerHTML='<option value="Semua">Semua Lembaga</option>';anchor.parentElement?.insertBefore(el,anchor)}const active=lembagaAktif();const current=el.value||active||"Semua";el.innerHTML='<option value="Semua">Semua Lembaga</option>';lembagaOptions().forEach(x=>{const o=document.createElement("option");o.value=x;o.textContent=x;el.appendChild(o)});if(active&&[...el.options].some(o=>o.value.toLowerCase()===active.toLowerCase()))el.value=active;else if([...el.options].some(o=>o.value.toLowerCase()===current.toLowerCase()))el.value=current;else el.value="Semua";el.onchange=()=>tampilkanDashboard()}
function sinkronkanFilterKategori(){const el=$("filterKategori");if(!el||!window.ckJenisKeuangan)return;window.ckJenisKeuangan.populate(el)}
function hitungDashboard(){const filter=$("filterKategori")?.value||"Semua";const lembaga=$("filterLembaga")?.value||lembagaAktif()||"Semua";const payments=semuaPembayaran.filter(i=>cocok(ambilLembaga(i),lembaga));const expenses=semuaPengeluaran.filter(i=>cocok(ambilLembaga(i),lembaga));const totalMasuk=payments.filter(i=>cocok(ambilKategoriPembayaran(i),filter)).reduce((s,i)=>s+ambilNominal(i),0);const totalKeluar=expenses.filter(i=>cocok(ambilKategoriPengeluaran(i),filter)).reduce((s,i)=>s+ambilNominalPengeluaran(i),0);return{totalMasuk,totalKeluar,saldo:totalMasuk-totalKeluar,totalSantri:semuaSantri.length,filter,lembaga}}
function tampilkanDashboard(){sinkronkanFilterKategori();pasangFilterLembaga();const h=hitungDashboard();["totalMasuk","pemasukan","jumlahPemasukan"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.totalMasuk)});["totalKeluar","pengeluaran","jumlahPengeluaran"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.totalKeluar)});["totalSaldo","saldo","saldoSaatIni"].forEach(id=>{if($(id))$(id).textContent=rupiah(h.saldo)});if($("totalSantri"))$("totalSantri").textContent=h.totalSantri.toLocaleString("id-ID");try{localStorage.setItem("catatanKasDashboard",JSON.stringify(h))}catch(_){}window.catatanKasDashboard=h}
function mulaiPembayaran(){if(unsubscribePayments)unsubscribePayments();unsubscribePayments=onSnapshot(collection(db,"payments"),s=>{semuaPembayaran=s.docs.map(d=>({id:d.id,...d.data()}));tampilkanDashboard();window.dispatchEvent(new CustomEvent("dataKeuanganBerubah",{detail:{tipe:"pembayaran"}}))},e=>console.error("Gagal membaca payments:",e))}
function mulaiPengeluaran(){if(unsubscribeExpenses)unsubscribeExpenses();unsubscribeExpenses=onSnapshot(collection(db,"expenses"),s=>{semuaPengeluaran=s.docs.map(d=>({id:d.id,...d.data()}));tampilkanDashboard();window.dispatchEvent(new CustomEvent("dataKeuanganBerubah",{detail:{tipe:"pengeluaran"}}))},e=>console.error("Gagal membaca expenses:",e))}
function bacaSantriLokal(){try{const d=JSON.parse(localStorage.getItem("daftarSantri")||"[]");return Array.isArray(d)?d.map((x,i)=>({id:x?.id??`local-${i}`,...x,source:"local"})).filter(x=>String(x?.nama||x?.namaSantri||"").trim()):[]}catch(_){return[]}}
function gabungkanSantri(cl,lo){const seen=new Set(),r=[];for(const i of [...cl,...lo]){const n=String(i?.nama||i?.namaSantri||i?.nama_santri||"").trim(),k=n.toLocaleLowerCase("id-ID").replace(/\s+/g," ");if(!k||seen.has(k))continue;seen.add(k);r.push({...i,nama:n})}return r}
function mulaiSantri(){if(unsubscribeSantri)unsubscribeSantri();unsubscribeSantri=onSnapshot(collection(db,"santri"),s=>{semuaSantri=gabungkanSantri(s.docs.map(d=>({id:d.id,...d.data(),source:"firestore"})),bacaSantriLokal());tampilkanDashboard()},e=>{console.error("Gagal membaca santri:",e);semuaSantri=bacaSantriLokal();tampilkanDashboard()})}
window.refreshDashboard=refreshLogoDanDashboard;window.addEventListener("dataKeuanganBerubah",()=>tampilkanDashboard());window.addEventListener("refreshDashboard",refreshLogoDanDashboard);window.addEventListener("logoDashboardChanged",muatLogoDashboard);window.addEventListener("storage",e=>{if(["catatanKasDataBerubah","logoDashboard","pengaturanAplikasi","jenisKeuanganCustom","daftarSantri"].includes(e.key)){mulaiSantri();refreshLogoDanDashboard()}});window.addEventListener("jenisKeuanganBerubah",()=>tampilkanDashboard());window.addEventListener("daftarSantriBerubah",()=>{mulaiSantri();refreshLogoDanDashboard()});
function pasangFilter(){const f=$("filterKategori");if(f)f.addEventListener("change",tampilkanDashboard)}
function pasangTombolDashboardExcel(){if(!document.body||$("btnDashboardExcelCatatanKas"))return;const menu=document.querySelector(".row.g-3.mb-4");if(!menu)return;const c=document.createElement("div");c.className="col-12";c.innerHTML='<a href="dashboard-excel.html" id="btnDashboardExcelCatatanKas" class="menu-btn" style="background:linear-gradient(135deg,#164c3d,#198754);color:#fff;border-color:#164c3d;"><i class="bi bi-file-earmark-spreadsheet" style="color:#fff;"></i><h6>Dashboard Excel</h6><small style="font-size:.68rem;opacity:.86;">Rekap pembayaran perorang</small></a>';const p=menu.querySelector("a[href='pengaturan.html']")?.closest(".col-12");p?menu.insertBefore(c,p):menu.appendChild(c)}
function initApp(){pasangFilter();muatLogoDashboard();tampilkanDashboard();pasangTombolDashboardExcel();mulaiPembayaran();mulaiPengeluaran();mulaiSantri()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initApp);else initApp();