import { db, auth } from "./firebase-config.js";
import { collection, query, where, getDocs, doc, getDoc, updateDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
let currentUser=null, transactions=[];
const amount=x=>Number(x?.nominal??x?.jumlah??x?.nilai??x?.total??0)||0;
const type=x=>String(x?.jenis??x?.kategori??"");
const name=x=>String(x?.namaSantri??x?.nama_santri??x?.nama??x?.keterangan??"-");
function dateValue(x){const v=x?.tanggal??x?.createdAt??x?.timestamp??x?.date;if(v?.toDate)return v.toDate();if(typeof v==='number')return new Date(v);if(typeof v==='string'){const d=new Date(v);if(!isNaN(d))return d}return null}
function dateText(x){const d=dateValue(x);return d?d.toLocaleDateString('id-ID'):'-'}
function dateInputValue(x){const d=dateValue(x);if(!d)return '';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
async function loadTransactions(){if(!currentUser)return;const [p,e]=await Promise.all([getDocs(query(collection(db,'payments'),where('uid','==',currentUser.uid))),getDocs(query(collection(db,'expenses'),where('uid','==',currentUser.uid)))]);transactions=[...p.docs.map(d=>({id:d.id,collection:'payments',...d.data()})),...e.docs.map(d=>({id:d.id,collection:'expenses',...d.data()}))]}
function mapRows(){const tbody=document.getElementById('rows');if(!tbody)return;const used=new Set();tbody.querySelectorAll('tr').forEach(row=>{if(row.dataset.transactionId)return;const c=row.querySelectorAll('td');if(c.length<5)return;const date=c[0].textContent.trim(),typ=c[2].textContent.trim().toLowerCase(),desc=c[3].textContent.trim(),n=Number(c[4].textContent.replace(/[^0-9]/g,''))||0;const found=transactions.find(x=>!used.has(x.id)&&dateText(x)===date&&type(x).trim().toLowerCase()===typ&&name(x).trim()===desc&&amount(x)===n);if(!found)return;used.add(found.id);row.dataset.transactionId=found.id;row.dataset.transactionCollection=found.collection;if(!row.dataset.reportActions){row.dataset.reportActions='1';const cell=document.createElement('td');cell.className='text-nowrap';cell.innerHTML='<button type="button" class="btn btn-sm btn-outline-primary me-1" data-report-edit title="Edit"><i class="bi bi-pencil"></i></button><button type="button" class="btn btn-sm btn-outline-danger" data-report-delete title="Hapus"><i class="bi bi-trash"></i></button>';row.appendChild(cell)}})}
async function own(id,c){if(!currentUser)throw new Error('Silakan login terlebih dahulu.');const s=await getDoc(doc(db,c,id));if(!s.exists())throw new Error('Transaksi tidak ditemukan.');if(s.data()?.uid&&s.data().uid!==currentUser.uid)throw new Error('Transaksi ini bukan milik akun Anda.');return s.data()}
async function edit(row){try{const c=row.dataset.transactionCollection,id=row.dataset.transactionId,d=await own(id,c),n=prompt('Edit nominal:',String(amount(d)));if(n===null)return;const nominal=Number(String(n).replace(/[^0-9]/g,''));if(!nominal)return alert('Nominal tidak valid.');const j=prompt('Edit jenis/kategori:',type(d));if(j===null||!j.trim())return;const k=prompt('Edit keterangan/nama:',name(d));if(k===null||!k.trim())return;const t=prompt('Edit tanggal (YYYY-MM-DD):',dateInputValue(d));if(t===null)return;await updateDoc(doc(db,c,id),{nominal,jumlah:nominal,jenis:j.trim(),kategori:j.trim(),nama:k.trim(),namaSantri:k.trim(),nama_santri:k.trim(),keterangan:k.trim(),tanggal:t||d.tanggal,updatedAt:new Date()});window.dispatchEvent(new CustomEvent('dataKeuanganBerubah',{detail:{tipe:'laporan-edit',uid:currentUser.uid}}));alert('Transaksi diperbarui. Riwayat, dashboard, dan laporan akan mengikuti data terbaru.');await loadTransactions();mapRows()}catch(e){console.error(e);alert(e.message||'Gagal mengedit transaksi.')}}
async function remove(row){try{const c=row.dataset.transactionCollection,id=row.dataset.transactionId,d=await own(id,c);if(!confirm(`Hapus transaksi ${name(d)} sebesar Rp ${amount(d).toLocaleString('id-ID')}?\n\nData laporan akan otomatis berubah.`))return;await deleteDoc(doc(db,c,id));window.dispatchEvent(new CustomEvent('dataKeuanganBerubah',{detail:{tipe:'laporan-hapus',uid:currentUser.uid}}));alert('Transaksi dihapus. Laporan mengikuti riwayat terbaru.');await loadTransactions();mapRows()}catch(e){console.error(e);alert(e.message||'Gagal menghapus transaksi.')}}
document.addEventListener('click',e=>{const ed=e.target.closest('[data-report-edit]'),del=e.target.closest('[data-report-delete]');if(ed){e.preventDefault();edit(ed.closest('tr'))}else if(del){e.preventDefault();remove(del.closest('tr'))}});
const observer=new MutationObserver(()=>mapRows());
function start(){if(!currentUser)return;loadTransactions().then(()=>{const tbody=document.getElementById('rows');if(tbody)observer.observe(tbody,{childList:true,subtree:true});mapRows()}).catch(console.error)}
onAuthStateChanged(auth,u=>{currentUser=u||null;if(currentUser)start()});
