import "./js/jenis-keuangan.js";
import "./js/data-cleanup.js";
import { db, auth } from "./firebase-config.js";
import { collection, addDoc, getDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";

let userAktif = null, idEdit = null, unsubscribe = null, authSelesai = false;
const $ = id => document.getElementById(id);
const ambil = ids => ids.map(id => $(id)).find(Boolean);
const nominal = x => Number(x?.nominal ?? x?.jumlah ?? x?.nilai ?? x?.total ?? 0) || 0;
const nama = x => String(x?.namaSiswaSiswi ?? x?.nama_siswa_siswi ?? x?.namaSiswa ?? x?.nama_siswa ?? x?.nama ?? x?.keterangan ?? "-");
const jenis = x => String(x?.jenis ?? x?.kategori ?? "Lainnya");
function compactUI(){if(document.getElementById("ckPaymentCompactStyle"))return;const s=document.createElement("style");s.id="ckPaymentCompactStyle";s.textContent=`#daftarPemasukan>div.ck-history-item{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:12px 10px!important;min-height:64px!important;line-height:1.2!important;font-size:.78rem!important}#daftarPemasukan .ck-history-info{min-width:0;flex:1}#daftarPemasukan small{font-size:.68rem!important;color:#728078!important;display:block!important;margin-bottom:4px!important}#daftarPemasukan strong{font-size:.8rem!important;display:block!important;overflow-wrap:anywhere!important}#daftarPemasukan .ck-history-right{flex:0 0 auto;text-align:right!important;min-width:120px}#daftarPemasukan .ck-history-amount{font-size:.84rem!important;font-weight:900!important;color:#198754!important;white-space:nowrap!important}#daftarPemasukan .ck-riwayat-actions{display:flex!important;justify-content:flex-end!important;gap:6px!important;margin-top:5px!important}#daftarPemasukan .ck-riwayat-actions button{width:34px!important;height:34px!important;min-width:34px!important;padding:4px!important;font-size:.8rem!important;line-height:1!important;border-radius:8px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;margin:0!important}@media(max-width:520px){#daftarPemasukan>div.ck-history-item{gap:8px!important;padding:10px 7px!important}#daftarPemasukan .ck-history-right{min-width:112px!important}#daftarPemasukan .ck-history-amount{font-size:.76rem!important}#daftarPemasukan strong{font-size:.74rem!important}#daftarPemasukan .ck-riwayat-actions{gap:5px!important}#daftarPemasukan .ck-riwayat-actions button{width:32px!important;height:32px!important;min-width:32px!important;font-size:.76rem!important}}`;document.head.appendChild(s)}
function localSettings(){try{const k=userAktif?.uid?`pengaturanAplikasi_${userAktif.uid}`:"pengaturanAplikasi";return{...JSON.parse(localStorage.getItem(k)||"{}")}}catch(_){return{}}}
async function lembagaAktif(){const local=localSettings(),localName=String(local.namaLembaga||local.namaPondok||local.lembaga||"").trim();if(localName)return localName;if(!userAktif)return"";try{const s=await getDoc(doc(db,"users",userAktif.uid)),p=s.exists()?s.data()?.pengaturan||{}:{};const name=String(p.namaLembaga||p.namaPondok||p.lembaga||"").trim();if(name){try{localStorage.setItem(`pengaturanAplikasi_${userAktif.uid}`,JSON.stringify({...local,...p,namaLembaga:name}))}catch(_){}return name}}catch(e){console.warn(e)}return""}
function refresh(){try{localStorage.setItem("catatanKasDataBerubah",String(Date.now()))}catch(_){}window.dispatchEvent(new Event("refreshDashboard"));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"));window.dispatchEvent(new CustomEvent("pemasukanBerubah"))}
function btn(){return ambil(["btnSimpanPemasukan","simpanPemasukan"])||document.querySelector("button[onclick*='simpanPemasukan']")}
function ensureYearUI(){if($("tahunPeriode"))return;const dari=$("bulanDari");if(!dari)return;const wrap=dari.closest(".row")||dari.parentElement?.parentElement;if(!wrap)return;const box=document.createElement("div");box.className="col-12 col-sm-6 mb-3";box.innerHTML='<label class="form-label" for="tahunPeriode">Tahun pembayaran</label><select id="tahunPeriode" class="form-select"></select>';const host=wrap.parentElement;host.insertBefore(box,wrap.nextElementSibling);const y=new Date().getFullYear();const el=$("tahunPeriode");for(let i=y-5;i<=y+5;i++){const o=document.createElement("option");o.value=String(i);o.textContent=String(i);if(i===y)o.selected=true;el.appendChild(o)}}
function reset(){idEdit=null;["namaSiswaSiswiPemasukan","namaSiswaSiswi","siswaSiswi","namaSiswa","nama","keterangan","jenis","jenisPemasukan","kategori","nominal","nominalPemasukan","jumlah","tanggalPemasukan","tanggal","tglPemasukan","bulanDari","bulanSampai"].forEach(id=>{const e=$(id);if(e)e.value=""});ensureYearUI();if($("tahunPeriode"))$("tahunPeriode").value=String(new Date().getFullYear());const j=ambil(["jenis","jenisPemasukan","kategori"]);window.ckJenisKeuangan?.reset(j);if(btn())btn().innerHTML="<i class='bi bi-save'></i> Simpan Pemasukan"}
function bulanData(){const dari=ambil(["bulanDari"]),sampai=ambil(["bulanSampai"]),tahun=$("tahunPeriode");return{bulanDari:dari?.value||"",bulanSampai:sampai?.value||"",bulanMulai:dari?.value||"",bulanAkhir:sampai?.value||"",tahun:tahun?.value||String(new Date().getFullYear()),tahunPembayaran:tahun?.value||String(new Date().getFullYear()),tahunPeriode:tahun?.value||String(new Date().getFullYear())}}
async function simpan(){if(!authSelesai||!userAktif)return alert("Akun belum siap. Tunggu sampai login selesai lalu coba lagi.");ensureYearUI();const lembaga=await lembagaAktif(),nEl=ambil(["namaSiswaSiswiPemasukan","namaSiswaSiswi","siswaSiswi","namaSiswa","nama","keterangan"]),jEl=ambil(["jenis","jenisPemasukan","kategori"]),nomEl=ambil(["nominal","nominalPemasukan","jumlah"]),dateEl=ambil(["tanggalPemasukan","tanggal","tglPemasukan"]),namaSiswaSiswi=nEl?.value.trim()||"",jenisPemasukan=window.ckJenisKeuangan?.resolve(jEl)||jEl?.value.trim()||"",n=Number(String(nomEl?.value||"").replace(/[^0-9]/g,""))||0,tanggal=dateEl?.value||null,periode=bulanData();if(!namaSiswaSiswi)return alert("Nama siswa/siswi / peserta didik / keterangan belum diisi.");if(!jenisPemasukan)return alert("Jenis pemasukan belum dipilih.");if(n<=0)return alert("Nominal pemasukan belum benar.");if(!periode.tahun)return alert("Tahun pembayaran belum dipilih.");if((periode.bulanDari&&!periode.bulanSampai)||(!periode.bulanDari&&periode.bulanSampai))return alert("Pilih bulan dari dan sampai dengan lengkap.");if(periode.bulanDari&&periode.bulanSampai&&Number(periode.bulanDari)>Number(periode.bulanSampai))return alert("Bulan mulai tidak boleh setelah bulan akhir.");const b=btn();try{if(b){b.disabled=true;b.dataset.saving="1"}const data={nama:namaSiswaSiswi,namaSiswaSiswi,nama_siswa_siswi:namaSiswaSiswi,namaSiswa:namaSiswaSiswi,keterangan:namaSiswaSiswi,jenis:jenisPemasukan,kategori:jenisPemasukan,nominal:n,jumlah:n,satuan:"Rupiah",tanggal,bulanDari:periode.bulanDari,bulanSampai:periode.bulanSampai,bulanMulai:periode.bulanMulai,bulanAkhir:periode.bulanAkhir,tahun:Number(periode.tahun),tahunPembayaran:Number(periode.tahun),tahunPeriode:Number(periode.tahun),uid:userAktif.uid,akunEmail:userAktif.email||"",lembaga:lembaga||"",lembagaNama:lembaga||"",updatedAt:serverTimestamp()};if(idEdit){const ref=doc(db,"payments",idEdit),old=await getDoc(ref);if(!old.exists()||old.data()?.uid!==userAktif.uid)return alert("Data ini bukan milik akun Anda.");await updateDoc(ref,data)}else{data.createdAt=serverTimestamp();await addDoc(collection(db,"payments"),data)}alert(idEdit?"Pemasukan berhasil diperbarui.":"Pemasukan berhasil disimpan.");reset();refresh()}catch(e){console.error(e);alert("Gagal menyimpan pemasukan.\n\n"+(e.message||e))}finally{if(b){b.disabled=false;delete b.dataset.saving}}}
window.simpanPemasukan=simpan;
window.editPemasukan=async id=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");ensureYearUI();const s=await getDoc(doc(db,"payments",id));if(!s.exists())return alert("Data pemasukan tidak ditemukan.");const d=s.data();if(d.uid&&d.uid!==userAktif.uid)return alert("Data ini milik akun lain.");idEdit=id;const n=ambil(["namaSiswaSiswiPemasukan","namaSiswaSiswi","siswaSiswi","namaSiswa","nama","keterangan"]),j=ambil(["jenis","jenisPemasukan","kategori"]),m=ambil(["nominal","nominalPemasukan","jumlah"]),t=ambil(["tanggalPemasukan","tanggal","tglPemasukan"]),bd=$("bulanDari"),bs=$("bulanSampai"),yr=$("tahunPeriode");if(n)n.value=nama(d);if(j){j.value=d.jenis||d.kategori||"";window.ckJenisKeuangan?.populate(j)}if(m)m.value=nominal(d);if(t)t.value=typeof d.tanggal==="string"?d.tanggal:"";if(bd)bd.value=String(d.bulanDari??d.bulanMulai??"");if(bs)bs.value=String(d.bulanSampai??d.bulanAkhir??"");if(yr)yr.value=String(d.tahun??d.tahunPembayaran??d.tahunPeriode??new Date().getFullYear());if(btn())btn().innerHTML="<i class='bi bi-save'></i> Simpan Perubahan"};
window.hapusPemasukan=async id=>{if(!userAktif)return;if(!confirm("Hapus pemasukan ini?"))return;const s=await getDoc(doc(db,"payments",id));if(!s.exists())return alert("Data tidak ditemukan.");if(s.data()?.uid&&s.data().uid!==userAktif.uid)return alert("Data ini milik akun lain.");await deleteDoc(doc(db,"payments",id));refresh()};
function render(s){const c=ambil(["daftarPemasukan","riwayatPemasukan","listPemasukan","riwayat"]);if(!c)return;compactUI();c.innerHTML=s.docs.map(d=>{const x={id:d.id,...d.data()},periode=x.bulanDari||x.bulanMulai?` · ${x.bulanDari||x.bulanMulai}-${x.bulanSampai||x.bulanAkhir||x.bulanDari||x.bulanMulai}`:"",tahun=x.tahun??x.tahunPembayaran??x.tahunPeriode??"";return `<div class="border-bottom ck-history-item"><div class="ck-history-info"><small>${String(x.tanggal||"-")} · ${jenis(x)}${periode}${tahun?` · ${tahun}`:""}</small><strong>${nama(x)}</strong></div><div class="ck-history-right"><div class="ck-history-amount">+Rp ${nominal(x).toLocaleString("id-ID")}</div><span class="ck-riwayat-actions"><button class="btn btn-sm btn-outline-primary" data-payment-action="edit" data-id="${x.id}" title="Edit" aria-label="Edit"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-danger" data-payment-action="delete" data-id="${x.id}" title="Hapus" aria-label="Hapus"><i class="bi bi-trash"></i></button></span></div></div>`}).join("")||'<div class="text-center text-muted p-2 small">Belum ada pemasukan untuk akun ini.</div>'}
document.addEventListener("click",e=>{const b=e.target.closest("[data-payment-action]");if(b){e.preventDefault();b.dataset.paymentAction==="edit"?editPemasukan(b.dataset.id):hapusPemasukan(b.dataset.id);return}const s=e.target.closest("#btnSimpanPemasukan,#simpanPemasukan,button[onclick*='simpanPemasukan']");if(s){e.preventDefault();e.stopImmediatePropagation();if(!s.dataset.saving)simpan()}},true);
document.addEventListener("submit",e=>{if(e.target.matches("form")&&e.target.querySelector("#btnSimpanPemasukan,#simpanPemasukan")){e.preventDefault();if(!btn()?.dataset.saving)simpan()}},true);
function mulaiPemasukan(){if(unsubscribe){unsubscribe();unsubscribe=null}if(!userAktif)return;const q=query(collection(db,"payments"),where("uid","==",userAktif.uid)),c=ambil(["daftarPemasukan","riwayatPemasukan","listPemasukan","riwayat"]);if(c)unsubscribe=onSnapshot(q,render,e=>{console.error(e);c.innerHTML='<div class="text-center text-danger p-2 small">Gagal memuat data akun.</div>'})}
onAuthStateChanged(auth,u=>{userAktif=u||null;authSelesai=true;ensureYearUI();mulaiPemasukan()});