import "./js/pembayaran-autocomplete.js";
import "./js/jenis-keuangan.js";
import "./js/data-cleanup.js";
import { db, auth } from "./firebase-config.js";
import { collection, addDoc, getDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
let userAktif=null,idEdit=null,unsubscribe=null;
const $=id=>document.getElementById(id),ambil=ids=>ids.map(id=>$(id)).find(Boolean);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const nominal=x=>Number(x?.nominal??x?.jumlah??x?.nilai??x?.total??0)||0;
const nama=x=>String(x?.namaSantri??x?.nama_santri??x?.nama??x?.keterangan??"-");
const jenis=x=>String(x?.jenis??x?.kategori??"Lainnya");
function settings(){try{return JSON.parse(localStorage.getItem("pengaturanAplikasi")||"{}")}catch(_){return {}}}
function lembagaAktif(){const s=settings();return String(s.namaLembaga||s.namaPondok||s.lembaga||"").trim()}
function refresh(){try{localStorage.setItem("catatanKasDataBerubah",String(Date.now()))}catch(_){}window.dispatchEvent(new Event("refreshDashboard"));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"))}
function btn(){return ambil(["btnSimpanPembayaran","simpanPembayaran"])||document.querySelector("button[onclick*='simpanPembayaran']")}
function reset(){idEdit=null;["namaSantriPemasukan","namaSantri","santri","nama","keterangan","jenis","jenisPembayaran","kategori","nominal","nominalPembayaran","jumlah","tanggalPembayaran","tanggal","tglPembayaran"].forEach(id=>{const e=$(id);if(e)e.value=""});const j=ambil(["jenis","jenisPembayaran","kategori"]);window.ckJenisKeuangan?.reset(j);if(btn())btn().innerHTML="Simpan Pembayaran"}
window.simpanPembayaran=async()=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");const lembaga=lembagaAktif();if(!lembaga)return alert("Silakan atur Nama Lembaga terlebih dahulu di Pengaturan.");const namaSantri=ambil(["namaSantriPemasukan","namaSantri","santri","nama","keterangan"])?.value.trim()||"",j=ambil(["jenis","jenisPembayaran","kategori"]),jenisPembayaran=window.ckJenisKeuangan?.resolve(j)||j?.value.trim()||"",n=Number(String(ambil(["nominal","nominalPembayaran","jumlah"])?.value||"").replace(/[^0-9]/g,""))||0,tanggal=ambil(["tanggalPembayaran","tanggal","tglPembayaran"])?.value||null;if(!namaSantri)return alert("Nama siswa / peserta didik / keterangan belum diisi.");if(!jenisPembayaran)return alert("Jenis pembayaran belum dipilih.");if(n<=0)return alert("Nominal pembayaran belum benar.");const b=btn();try{if(b)b.disabled=true;const data={nama:namaSantri,namaSantri,nama_santri:namaSantri,keterangan:namaSantri,jenis:jenisPembayaran,kategori:jenisPembayaran,nominal:n,jumlah:n,satuan:"Rupiah",tanggal,uid:userAktif.uid,akunEmail:userAktif.email||"",lembaga,lembagaNama:lembaga,updatedAt:serverTimestamp()};if(idEdit){const old=await getDoc(doc(db,"payments",idEdit));const od=old.exists()?old.data():{};if(od.uid&&od.uid!==userAktif.uid)return alert("Data ini milik akun lain dan tidak dapat diubah.");data.uid=od.uid||userAktif.uid;data.akunEmail=od.akunEmail||userAktif.email||"";data.lembaga=od.lembaga||od.lembagaNama||lembaga;data.lembagaNama=od.lembagaNama||od.lembaga||lembaga;await updateDoc(doc(db,"payments",idEdit),data)}else{data.createdAt=serverTimestamp();await addDoc(collection(db,"payments"),data)}alert(idEdit?"Pembayaran berhasil diperbarui.":"Pembayaran berhasil disimpan.");reset();refresh()}catch(e){alert("Gagal menyimpan pembayaran.\n\n"+(e.message||e))}finally{if(b)b.disabled=false}};
window.editPembayaran=async id=>{const s=await getDoc(doc(db,"payments",id));if(!s.exists())return alert("Data pembayaran tidak ditemukan.");const d=s.data();if(d.uid&&d.uid!==userAktif?.uid)return alert("Data ini milik akun lain.");idEdit=id;const n=ambil(["namaSantriPemasukan","namaSantri","santri","nama","keterangan"]),j=ambil(["jenis","jenisPembayaran","kategori"]),m=ambil(["nominal","nominalPembayaran","jumlah"]),t=ambil(["tanggalPembayaran","tanggal","tglPembayaran"]);if(n)n.value=nama(d);if(j){j.value=d.jenis||d.kategori||"";window.ckJenisKeuangan?.populate(j)}if(m)m.value=nominal(d);if(t)t.value=typeof d.tanggal==="string"?d.tanggal:"";if(btn())btn().innerHTML="Simpan Perubahan"};window.hapusPembayaran=async id=>{if(!userAktif)return;if(!confirm("Hapus pembayaran ini?"))return;const s=await getDoc(doc(db,"payments",id));if(!s.exists())return alert("Data tidak ditemukan.");if(s.data()?.uid&&s.data().uid!==userAktif.uid)return alert("Data ini milik akun lain.");await deleteDoc(doc(db,"payments",id));refresh()};
function render(s){const c=ambil(["daftarPembayaran","riwayatPembayaran","listPembayaran","riwayat"]);if(!c)return;c.innerHTML=s.docs.map(d=>{const x={id:d.id,...d.data()};return `<div class="border-bottom p-2"><small>${esc(x.tanggal||"-")} · ${esc(jenis(x))}</small><br><strong>${esc(nama(x))}</strong>${x.lembagaNama?`<div class="small text-muted">Lembaga: ${esc(x.lembagaNama)}</div>`:""}<div class="text-success fw-bold">+${rp(nominal(x))}</div><button class="btn btn-sm btn-outline-primary" data-payment-action="edit" data-id="${esc(x.id)}">Edit</button> <button class="btn btn-sm btn-outline-danger" data-payment-action="delete" data-id="${esc(x.id)}">Hapus</button></div>`}).join("")||'<div class="text-center text-muted p-4">Belum ada pemasukan untuk akun ini.</div>'}
const rp=x=>"Rp "+nominal({nominal:x}).toLocaleString("id-ID");
document.addEventListener("click",e=>{const b=e.target.closest("[data-payment-action]");if(!b)return;e.preventDefault();b.dataset.paymentAction==="edit"?editPembayaran(b.dataset.id):hapusPembayaran(b.dataset.id)});
function mulaiPembayaran(){if(unsubscribe){unsubscribe();unsubscribe=null}if(!userAktif)return;const q=query(collection(db,"payments"),where("uid","==",userAktif.uid));const c=ambil(["daftarPembayaran","riwayatPembayaran","listPembayaran","riwayat"]);if(c)unsubscribe=onSnapshot(q,render,e=>{console.error(e);c.innerHTML='<div class="text-center text-danger p-4">Gagal memuat data akun.</div>'})}
document.addEventListener("DOMContentLoaded",()=>{btn()?.addEventListener("click",e=>{e.preventDefault();window.simpanPembayaran()});});
onAuthStateChanged(auth,u=>{userAktif=u||null;mulaiPembayaran()});