import "./js/pembayaran-autocomplete.js";
import "./js/jenis-keuangan.js";
import "./js/data-cleanup.js";
import { db, auth } from "./firebase-config.js";
import { collection, addDoc, getDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
let userAktif=null,idEdit=null,unsubscribe=null,authSelesai=false;
const $=id=>document.getElementById(id),ambil=ids=>ids.map(id=>$(id)).find(Boolean);
const nominal=x=>Number(x?.nominal??x?.jumlah??x?.nilai??x?.total??0)||0;
const nama=x=>String(x?.namaSantri??x?.nama_santri??x?.nama??x?.keterangan??"-");
const jenis=x=>String(x?.jenis??x?.kategori??"Lainnya");
function compactUI(){if(document.getElementById("ckPaymentCompactStyle"))return;const s=document.createElement("style");s.id="ckPaymentCompactStyle";s.textContent=`#daftarPembayaran>div.ck-history-item{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:12px 10px!important;min-height:64px!important;line-height:1.2!important;font-size:.78rem!important}#daftarPembayaran .ck-history-info{min-width:0;flex:1}#daftarPembayaran small{font-size:.68rem!important;color:#728078!important;display:block!important;margin-bottom:4px!important}#daftarPembayaran strong{font-size:.8rem!important;display:block!important;overflow-wrap:anywhere!important}#daftarPembayaran .ck-history-right{flex:0 0 auto;text-align:right!important;min-width:120px}#daftarPembayaran .ck-history-amount{font-size:.84rem!important;font-weight:900!important;color:#198754!important;white-space:nowrap!important}#daftarPembayaran .ck-riwayat-actions{display:flex!important;justify-content:flex-end!important;gap:5px!important;margin-top:5px!important}#daftarPembayaran .ck-riwayat-actions button{width:28px!important;height:28px!important;padding:3px!important;font-size:.68rem!important;line-height:1!important;border-radius:7px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;margin:0!important}@media(max-width:520px){#daftarPembayaran>div.ck-history-item{gap:8px!important;padding:10px 7px!important}#daftarPembayaran .ck-history-right{min-width:105px!important}#daftarPembayaran .ck-history-amount{font-size:.76rem!important}#daftarPembayaran strong{font-size:.74rem!important}}`;document.head.appendChild(s)}
function localSettings(){try{const k=userAktif?.uid?`pengaturanAplikasi_${userAktif.uid}`:"pengaturanAplikasi";return {...JSON.parse(localStorage.getItem(k)||"{}")}}catch(_){return {}}}
async function lembagaAktif(){const local=localSettings();const localName=String(local.namaPondok||local.namaLembaga||local.lembaga||"").trim();if(localName)return localName;if(!userAktif)return "";try{const s=await getDoc(doc(db,"users",userAktif.uid));const p=s.exists()?s.data()?.pengaturan||{}:{};const name=String(p.namaPondok||p.namaLembaga||p.lembaga||"").trim();if(name){try{localStorage.setItem(`pengaturanAplikasi_${userAktif.uid}`,JSON.stringify({...local,...p,namaPondok:name}))}catch(_){}return name}}catch(e){console.warn(e)}return ""}
function refresh(){try{localStorage.setItem("catatanKasDataBerubah",String(Date.now()))}catch(_){}window.dispatchEvent(new Event("refreshDashboard"));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"));window.dispatchEvent(new CustomEvent("pembayaranBerubah"))}
function btn(){return ambil(["btnSimpanPembayaran","simpanPembayaran"])||document.querySelector("button[onclick*='simpanPembayaran']")}
function reset(){idEdit=null;["namaSantriPemasukan","namaSantri","santri","nama","keterangan","jenis","jenisPembayaran","kategori","nominal","nominalPembayaran","jumlah","tanggalPembayaran","tanggal","tglPembayaran","bulanDari","bulanSampai"].forEach(id=>{const e=$(id);if(e)e.value=""});const j=ambil(["jenis","jenisPembayaran","kategori"]);window.ckJenisKeuangan?.reset(j);if(btn())btn().innerHTML="<i class='bi bi-save'></i> Simpan Pembayaran"}
function bulanData(){const dari=ambil(["bulanDari"]),sampai=ambil(["bulanSampai"]);return{bulanDari:dari?.value||"",bulanSampai:sampai?.value||"",bulanMulai:dari?.value||"",bulanAkhir:sampai?.value||""}}
async function simpan(){if(!authSelesai||!userAktif)return alert("Akun belum siap. Tunggu sampai login selesai lalu coba lagi.");const lembaga=await lembagaAktif(),nEl=ambil(["namaSantriPemasukan","namaSantri","santri","nama","keterangan"]),jEl=ambil(["jenis","jenisPembayaran","kategori"]),nomEl=ambil(["nominal","nominalPembayaran","jumlah"]),dateEl=ambil(["tanggalPembayaran","tanggal","tglPembayaran"]),namaSantri=nEl?.value.trim()||"",jenisPembayaran=window.ckJenisKeuangan?.resolve(jEl)||jEl?.value.trim()||"",n=Number(String(nomEl?.value||"").replace(/[^0-9]/g,""))||0,tanggal=dateEl?.value||null,periode=bulanData();if(!namaSantri)return alert("Nama siswa / peserta didik / keterangan belum diisi.");if(!jenisPembayaran)return alert("Jenis pembayaran belum dipilih.");if(n<=0)return alert("Nominal pembayaran belum benar.");if((periode.bulanDari&&!periode.bulanSampai)||(!periode.bulanDari&&periode.bulanSampai))return alert("Pilih bulan dari dan sampai dengan lengkap.");if(periode.bulanDari&&periode.bulanSampai&&Number(periode.bulanDari)>Number(periode.bulanSampai))return alert("Bulan mulai tidak boleh setelah bulan akhir.");const b=btn();try{if(b){b.disabled=true;b.dataset.saving="1"}const data={nama:namaSantri,namaSantri,nama_santri:namaSantri,keterangan:namaSantri,jenis:jenisPembayaran,kategori:jenisPembayaran,nominal:n,jumlah:n,satuan:"Rupiah",tanggal,bulanDari:periode.bulanDari,bulanSampai:periode.bulanSampai,bulanMulai:periode.bulanMulai,bulanAkhir:periode.bulanAkhir,uid:userAktif.uid,akunEmail:userAktif.email||"",lembaga:lembaga||"",lembagaNama:lembaga||"",updatedAt:serverTimestamp()};if(idEdit){const ref=doc(db,"payments",idEdit),old=await getDoc(ref);if(!old.exists()||old.data()?.uid!==userAktif.uid)return alert("Data ini bukan milik akun Anda.");await updateDoc(ref,data)}else{data.createdAt=serverTimestamp();await addDoc(collection(db,"payments"),data)}alert(idEdit?"Pembayaran berhasil diperbarui.":"Pembayaran berhasil disimpan.");reset();refresh()}catch(e){console.error(e);alert("Gagal menyimpan pembayaran.\n\n"+(e.message||e))}finally{if(b){b.disabled=false;delete b.dataset.saving}}}
window.simpanPembayaran=simpan;
window.editPembayaran=async id=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");const s=await getDoc(doc(db,"payments",id));if(!s.exists())return alert("Data pembayaran tidak ditemukan.");const d=s.data();if(d.uid&&d.uid!==userAktif.uid)return alert("Data ini milik akun lain.");idEdit=id;const n=ambil(["namaSantriPemasukan","namaSantri","santri","nama","keterangan"]),j=ambil(["jenis","jenisPembayaran","kategori"]),m=ambil(["nominal","nominalPembayaran","jumlah"]),t=ambil(["tanggalPembayaran","tanggal","tglPembayaran"]),bd=$("bulanDari"),bs=$("bulanSampai");if(n)n.value=nama(d);if(j){j.value=d.jenis||d.kategori||"";window.ckJenisKeuangan?.populate(j)}if(m)m.value=nominal(d);if(t)t.value=typeof d.tanggal==="string"?d.tanggal:"";if(bd)bd.value=String(d.bulanDari??d.bulanMulai??"");if(bs)bs.value=String(d.bulanSampai??d.bulanAkhir??"");if(btn())btn().innerHTML="<i class='bi bi-save'></i> Simpan Perubahan"};
window.hapusPembayaran=async id=>{if(!userAktif)return;if(!confirm("Hapus pembayaran ini?"))return;const s=await getDoc(doc(db,"payments",id));if(!s.exists())return alert("Data tidak ditemukan.");if(s.data()?.uid&&s.data().uid!==userAktif.uid)return alert("Data ini milik akun lain.");await deleteDoc(doc(db,"payments",id));refresh()};
function render(s){const c=ambil(["daftarPembayaran","riwayatPembayaran","listPembayaran","riwayat"]);if(!c)return;compactUI();c.innerHTML=s.docs.map(d=>{const x={id:d.id,...d.data()},periode=x.bulanDari||x.bulanMulai?` · ${x.bulanDari||x.bulanMulai}-${x.bulanSampai||x.bulanAkhir||x.bulanDari||x.bulanMulai}`:"";return `<div class="border-bottom ck-history-item"><div class="ck-history-info"><small>${String(x.tanggal||"-")} · ${jenis(x)}${periode}</small><strong>${nama(x)}</strong></div><div class="ck-history-right"><div class="ck-history-amount">+Rp ${nominal(x).toLocaleString("id-ID")}</div><span class="ck-riwayat-actions"><button class="btn btn-sm btn-outline-primary" data-payment-action="edit" data-id="${x.id}" title="Edit" aria-label="Edit"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-danger" data-payment-action="delete" data-id="${x.id}" title="Hapus" aria-label="Hapus"><i class="bi bi-trash"></i></button></span></div></div>`}).join("")||'<div class="text-center text-muted p-2 small">Belum ada pemasukan untuk akun ini.</div>'}
document.addEventListener("click",e=>{const b=e.target.closest("[data-payment-action]");if(b){e.preventDefault();b.dataset.paymentAction==="edit"?editPembayaran(b.dataset.id):hapusPembayaran(b.dataset.id);return}const s=e.target.closest("#btnSimpanPembayaran,#simpanPembayaran,button[onclick*='simpanPembayaran']");if(s){e.preventDefault();e.stopImmediatePropagation();if(!s.dataset.saving)simpan()}},true);
document.addEventListener("submit",e=>{if(e.target.matches("form")&&e.target.querySelector("#btnSimpanPembayaran,#simpanPembayaran")){e.preventDefault();if(!btn()?.dataset.saving)simpan()}},true);
function mulaiPembayaran(){if(unsubscribe){unsubscribe();unsubscribe=null}if(!userAktif)return;const q=query(collection(db,"payments"),where("uid","==",userAktif.uid));const c=ambil(["daftarPembayaran","riwayatPembayaran","listPembayaran","riwayat"]);if(c)unsubscribe=onSnapshot(q,render,e=>{console.error(e);c.innerHTML='<div class="text-center text-danger p-2 small">Gagal memuat data akun.</div>'})}
onAuthStateChanged(auth,u=>{userAktif=u||null;authSelesai=true;mulaiPembayaran()});