import "./js/jenis-keuangan.js";
import "./js/data-cleanup.js";
import { db, auth } from "./firebase-config.js";
import { collection, addDoc, getDoc, updateDoc, deleteDoc, doc, onSnapshot, serverTimestamp, query, where } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
let userAktif=null,idEdit=null,unsubscribe=null,authSelesai=false;
const $=id=>document.getElementById(id),ambil=ids=>ids.map(id=>$(id)).find(Boolean);
const amount=x=>Number(x?.nominal??x?.jumlah??x?.nilai??x?.total??0)||0;const jenis=x=>String(x?.jenis??x?.kategori??"Lainnya");const ket=x=>String(x?.keterangan??x?.nama??x?.deskripsi??x?.uraian??"Pengeluaran");
function compactUI(){if(document.getElementById("ckExpenseCompactStyle"))return;const s=document.createElement("style");s.id="ckExpenseCompactStyle";s.textContent=`#daftarPengeluaran>div{padding:5px 7px!important;line-height:1.1;font-size:.62rem!important;position:relative}#daftarPengeluaran small{font-size:.54rem!important;color:#728078}#daftarPengeluaran strong{font-size:.64rem!important}#daftarPengeluaran .text-danger{font-size:.66rem!important}#daftarPengeluaran .ck-riwayat-actions{display:inline-flex!important;gap:3px!important;align-items:center!important;vertical-align:middle!important;margin-left:5px!important}#daftarPengeluaran .ck-riwayat-actions button{width:24px!important;height:24px!important;padding:2px!important;font-size:.62rem!important;line-height:1!important;border-radius:6px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;margin:0!important}`;document.head.appendChild(s)}
function localSettings(){try{const k=userAktif?.uid?`pengaturanAplikasi_${userAktif.uid}`:"pengaturanAplikasi";return JSON.parse(localStorage.getItem(k)||"{}")}catch(_){return {}}}
async function lembagaAktif(){const local=localSettings();const localName=String(local.namaPondok||local.namaLembaga||local.lembaga||"").trim();if(localName)return localName;if(!userAktif)return "";try{const s=await getDoc(doc(db,"users",userAktif.uid));const p=s.exists()?s.data()?.pengaturan||{}:{};const name=String(p.namaPondok||p.namaLembaga||p.lembaga||"").trim();if(name){try{localStorage.setItem(`pengaturanAplikasi_${userAktif.uid}`,JSON.stringify({...local,...p,namaPondok:name}))}catch(_){}return name}}catch(e){console.warn(e)}return ""}
function refresh(){try{localStorage.setItem("catatanKasDataBerubah",String(Date.now()))}catch(_){}window.dispatchEvent(new Event("refreshDashboard"));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"));window.dispatchEvent(new CustomEvent("pengeluaranBerubah"))}
function btn(){return ambil(["btnSimpanPengeluaran","simpanPengeluaran"])||document.querySelector("button[onclick*='simpanPengeluaran']")}
function reset(){idEdit=null;["keteranganPengeluaran","keterangan","namaPengeluaran","nama","deskripsi","jenisPengeluaran","jenis","kategoriPengeluaran","kategori","nominalPengeluaran","nominal","jumlah","total","tanggalPengeluaran","tanggal","tglPengeluaran","satuanPengeluaran","satuan"].forEach(id=>{const e=$(id);if(e)e.value=""});const j=ambil(["jenisPengeluaran","jenis","kategoriPengeluaran","kategori"]);window.ckJenisKeuangan?.reset(j);const s=ambil(["satuanPengeluaran","satuan"]);if(s)s.value="Rupiah";if(btn())btn().innerHTML="Simpan Pengeluaran"}
async function simpan(){if(!authSelesai||!userAktif)return alert("Akun belum siap. Tunggu sampai login selesai lalu coba lagi.");const lembaga=await lembagaAktif();const kEl=ambil(["keteranganPengeluaran","keterangan","namaPengeluaran","nama","deskripsi"]),jEl=ambil(["jenisPengeluaran","jenis","kategoriPengeluaran","kategori"]),nEl=ambil(["nominalPengeluaran","nominal","jumlah","total"]),tEl=ambil(["tanggalPengeluaran","tanggal","tglPengeluaran"]),sEl=ambil(["satuanPengeluaran","satuan"]);const k=kEl?.value.trim()||"",jenisPengeluaran=window.ckJenisKeuangan?.resolve(jEl)||jEl?.value.trim()||"",n=Number(String(nEl?.value||"").replace(/[^0-9]/g,""))||0,t=tEl?.value||null,s=sEl?.value||"Rupiah";if(!k)return alert("Keterangan pengeluaran belum diisi.");if(!jenisPengeluaran)return alert("Jenis pengeluaran belum dipilih.");if(n<=0)return alert("Nominal pengeluaran belum benar.");const b=btn();try{if(b){b.disabled=true;b.dataset.saving="1"}const data={keterangan:k,nama:k,deskripsi:k,jenis:jenisPengeluaran,kategori:jenisPengeluaran,nominal:n,jumlah:n,total:n,satuan:s,tanggal:t,uid:userAktif.uid,akunEmail:userAktif.email||"",lembaga:lembaga||"",lembagaNama:lembaga||"",updatedAt:serverTimestamp()};if(idEdit){const ref=doc(db,"expenses",idEdit),old=await getDoc(ref);if(!old.exists()||old.data()?.uid!==userAktif.uid)return alert("Data ini bukan milik akun Anda.");await updateDoc(ref,data)}else{data.createdAt=serverTimestamp();await addDoc(collection(db,"expenses"),data)}alert(idEdit?"Pengeluaran berhasil diperbarui.":"Pengeluaran berhasil disimpan.");reset();refresh()}catch(e){console.error(e);alert("Gagal menyimpan pengeluaran.\n\n"+(e.message||e))}finally{if(b){b.disabled=false;delete b.dataset.saving}}}
window.simpanPengeluaran=simpan;
window.editPengeluaran=async id=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");const s=await getDoc(doc(db,"expenses",id));if(!s.exists())return alert("Data pengeluaran tidak ditemukan.");const d=s.data();if(d.uid&&d.uid!==userAktif.uid)return alert("Data ini milik akun lain.");idEdit=id;const k=ambil(["keteranganPengeluaran","keterangan","namaPengeluaran","nama","deskripsi"]),j=ambil(["jenisPengeluaran","jenis","kategoriPengeluaran","kategori"]),n=ambil(["nominalPengeluaran","nominal","jumlah","total"]),t=ambil(["tanggalPengeluaran","tanggal","tglPengeluaran"]),sat=ambil(["satuanPengeluaran","satuan"]);if(k)k.value=ket(d);if(j){j.value=d.jenis||d.kategori||"";window.ckJenisKeuangan?.populate(j)}if(n)n.value=amount(d);if(t)t.value=typeof d.tanggal==="string"?d.tanggal:"";if(sat)sat.value=d.satuan||"Rupiah";if(btn())btn().innerHTML="Simpan Perubahan"};
window.hapusPengeluaran=async id=>{if(!userAktif)return;if(!confirm("Hapus data pengeluaran ini?"))return;const s=await getDoc(doc(db,"expenses",id));if(!s.exists())return alert("Data tidak ditemukan.");if(s.data()?.uid&&s.data().uid!==userAktif.uid)return alert("Data ini milik akun lain.");await deleteDoc(doc(db,"expenses",id));refresh()};
function render(s){const c=$("daftarPengeluaran");if(!c)return;compactUI();c.innerHTML=s.docs.map(d=>{const x={id:d.id,...d.data()};return `<div class="border-bottom"><small>${String(x.tanggal||"-")} · ${jenis(x)}</small><br><strong>${ket(x)}</strong><div class="text-danger fw-bold">-Rp ${amount(x).toLocaleString("id-ID")}</div><span class="ck-riwayat-actions"><button class="btn btn-sm btn-outline-primary" data-expense-action="edit" data-id="${x.id}" title="Edit" aria-label="Edit"><i class="bi bi-pencil"></i></button><button class="btn btn-sm btn-outline-danger" data-expense-action="delete" data-id="${x.id}" title="Hapus" aria-label="Hapus"><i class="bi bi-trash"></i></button></span></div>`}).join("")||'<div class="text-center text-muted p-2 small">Belum ada pengeluaran untuk akun ini.</div>'}
document.addEventListener("click",e=>{const b=e.target.closest("[data-expense-action]");if(b){e.preventDefault();b.dataset.expenseAction==="edit"?editPengeluaran(b.dataset.id):hapusPengeluaran(b.dataset.id);return}const s=e.target.closest("#btnSimpanPengeluaran,#simpanPengeluaran,button[onclick*='simpanPengeluaran']");if(s){e.preventDefault();e.stopImmediatePropagation();if(!s.dataset.saving)simpan()}},true);
document.addEventListener("submit",e=>{if(e.target.matches("form")&&e.target.querySelector("#btnSimpanPengeluaran,#simpanPengeluaran")){e.preventDefault();if(!btn()?.dataset.saving)simpan()}},true);
function mulaiPengeluaran(){if(unsubscribe){unsubscribe();unsubscribe=null}if(!userAktif)return;const q=query(collection(db,"expenses"),where("uid","==",userAktif.uid));const c=$("daftarPengeluaran");if(c)unsubscribe=onSnapshot(q,render,e=>{console.error(e);c.innerHTML='<div class="text-center text-danger p-2 small">Gagal memuat data akun.</div>'})}
onAuthStateChanged(auth,u=>{userAktif=u||null;authSelesai=true;mulaiPengeluaran()});