import { db, auth } from "./firebase-config.js";
import { collection, addDoc, getDocs, updateDoc, deleteDoc, doc, serverTimestamp, query, where, onSnapshot, getDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
const $=id=>document.getElementById(id);const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));let userAktif=null,unsubscribe=null;
function logoDashboard(){return window.CatatanKasSettings?.getLogo?.()||"logo-catatan-kas.jpg"}function muatLogo(){const logo=logoDashboard();document.querySelectorAll(".app-logo,.ck-logo,#logoDashboard,#dashboardLogo,#logoPreviewV2,#logoPreview,img[alt='Logo Dashboard'],img[alt='Logo aplikasi'],[data-dashboard-logo]").forEach(img=>{if(img?.tagName==="IMG"){img.src=logo;img.removeAttribute("srcset")}})}
const inputId=(...ids)=>ids.map(id=>$(id)).find(Boolean);const namaInput=()=>inputId("nama","namaSantri");const kelasInput=()=>inputId("kelas","kelasSantri");const waliInput=()=>inputId("wali","hpSantri");const idInput=()=>$("idSantri");
const cacheKey=()=>userAktif?.uid?`daftarSantri_${userAktif.uid}`:"daftarSantri";
function readCache(){try{const x=JSON.parse(localStorage.getItem(cacheKey())||"[]");return Array.isArray(x)?x:[]}catch(_){return []}}
function writeCache(list){try{localStorage.setItem(cacheKey(),JSON.stringify(list.map(x=>({id:x.id||"",nama:String(x.nama||"").trim(),kelas:String(x.kelas||"-").trim()||"-",wali:String(x.wali||"-").trim()||"-"})).filter(x=>x.nama)))}catch(_){} }
function mergeCache(list){const old=readCache(),map=new Map(old.filter(x=>x.nama).map(x=>[String(x.id||x.nama),x]));list.forEach(x=>map.set(String(x.id||x.nama),x));return [...map.values()]}
function kosongkan(){["nama","namaSantri","kelas","kelasSantri","wali","hpSantri","idSantri"].forEach(id=>{if($(id))$(id).value=""});const b=document.querySelector("button[onclick*='simpanSantri'],#btnSimpanSantri");if(b)b.innerHTML="Simpan Peserta Didik"}
function refresh(){try{localStorage.setItem("catatanKasDataBerubah",String(Date.now()))}catch(_){}window.dispatchEvent(new CustomEvent("daftarSantriBerubah"));window.dispatchEvent(new CustomEvent("dataKeuanganBerubah"))}
function renderList(list){const el=$("daftarSantri"),tbody=$("tbodySantri"),jumlah=$("jumlahSantri");if(jumlah)jumlah.textContent=list.length+" santri";if(el)el.innerHTML=list.length?list.map((x,i)=>`<li class="list-group-item d-flex justify-content-between align-items-center py-3 gap-2"><div class="flex-grow-1"><b class="d-block text-dark">${i+1}. ${esc(x.nama)}</b><small class="text-muted">Kelas: ${esc(x.kelas||"-")} • Wali: ${esc(x.wali||"-")}</small></div><div class="d-flex gap-1"><button type="button" class="btn btn-outline-primary btn-sm" data-santri-action="edit" data-id="${esc(x.id)}"><i class="bi bi-pencil"></i></button><button type="button" class="btn btn-outline-danger btn-sm" data-santri-action="delete" data-id="${esc(x.id)}"><i class="bi bi-trash"></i></button></div></li>`).join(""):'<li class="list-group-item text-center text-muted py-3">Belum ada data peserta didik.</li>';if(tbody)tbody.innerHTML=list.length?list.map((x,i)=>`<tr><td>${i+1}</td><td class="nama-santri">${esc(x.nama)}</td><td class="kelas-santri">${esc(x.kelas||"-")}</td><td class="text-center"><button type="button" class="btn btn-outline-primary btn-sm me-1" data-santri-action="edit" data-id="${esc(x.id)}"><i class="bi bi-pencil"></i></button><button type="button" class="btn btn-outline-danger btn-sm" data-santri-action="delete" data-id="${esc(x.id)}"><i class="bi bi-trash"></i></button></td></tr>`).join(""):'<tr><td colspan="4" class="text-center text-muted py-4">Belum ada data peserta didik.</td></tr>'}
function render(snap){const list=snap.docs.map(d=>({id:d.id,...d.data()}));writeCache(list);renderList(list)}
async function load(){const el=$("daftarSantri"),tbody=$("tbodySantri");if(!el&&!tbody)return;if(unsubscribe){unsubscribe();unsubscribe=null}if(!userAktif){renderList(readCache());return}const cached=readCache();if(cached.length)renderList(cached);else{if(el)el.innerHTML='<li class="list-group-item text-center text-muted py-3">Memuat data peserta didik...</li>';if(tbody)tbody.innerHTML='<tr><td colspan="4" class="text-center text-muted py-4">Memuat data peserta didik...</td></tr>'}const q=query(collection(db,"santri"),where("uid","==",userAktif.uid));try{const first=await getDocs(q);if(auth.currentUser?.uid===userAktif.uid)render(first);unsubscribe=onSnapshot(q,s=>{if(auth.currentUser?.uid===userAktif.uid)render(s)},e=>{console.warn("Firestore santri listener:",e);const c=readCache();if(c.length)renderList(c);else{const msg=`Gagal memuat data peserta didik.<br><small>${esc(e?.message||"Firestore error")}</small>`;if(el)el.innerHTML=`<li class="list-group-item text-center text-danger py-3">${msg}</li>`;if(tbody)tbody.innerHTML=`<tr><td colspan="4" class="text-center text-danger py-4">${msg}</td></tr>`}})}catch(e){console.error(e);const c=readCache();if(c.length)renderList(c);else{const msg=`Gagal memuat data peserta didik.<br><small>${esc(e?.message||"Firestore error")}</small>`;if(el)el.innerHTML=`<li class="list-group-item text-center text-danger py-3">${msg}</li>`;if(tbody)tbody.innerHTML=`<tr><td colspan="4" class="text-center text-danger py-4">${msg}</td></tr>`}}}
window.simpanSantri=async()=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");const nama=namaInput()?.value.trim()||"",kelas=kelasInput()?.value.trim()||"-",wali=waliInput()?.value.trim()||"-",id=idInput()?.value||"";if(!nama)return alert("Silakan isi nama peserta didik.");try{if(id){const ref=doc(db,"santri",id),old=await getDoc(ref);if(!old.exists()||old.data()?.uid!==userAktif.uid)return alert("Data ini bukan milik akun Anda.");await updateDoc(ref,{nama,kelas,wali,updatedAt:serverTimestamp(),uid:userAktif.uid});writeCache(readCache().map(x=>x.id===id?{...x,id,nama,kelas,wali}:x))}else{const ref=await addDoc(collection(db,"santri"),{nama,kelas,wali,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),uid:userAktif.uid,akunEmail:userAktif.email||""});writeCache(mergeCache([{id:ref.id,nama,kelas,wali}]))}kosongkan();refresh();alert(id?"Data peserta didik berhasil diperbarui.":"Peserta didik berhasil ditambahkan.")}catch(e){alert("Gagal menyimpan data peserta didik.\n\n"+(e.message||e))}};
window.editSantri=async id=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");try{const s=await getDoc(doc(db,"santri",id));if(!s.exists()||s.data()?.uid!==userAktif.uid)return alert("Data peserta didik tidak ditemukan pada akun ini.");const d=s.data();if(namaInput())namaInput().value=d.nama||"";if(kelasInput())kelasInput().value=d.kelas||"";if(waliInput())waliInput().value=d.wali||"";if(idInput())idInput().value=id;const b=document.querySelector("button[onclick*='simpanSantri'],#btnSimpanSantri");if(b)b.innerHTML="Simpan Perubahan";window.scrollTo({top:0,behavior:"smooth"})}catch(e){alert("Gagal membuka data peserta didik.\n\n"+(e.message||e))}};
window.hapusSantri=async id=>{if(!userAktif)return alert("Silakan login terlebih dahulu.");if(!confirm("Hapus data peserta didik ini?\n\nData yang dihapus tidak dapat dikembalikan."))return;try{const ref=doc(db,"santri",id),s=await getDoc(ref);if(!s.exists()||s.data()?.uid!==userAktif.uid)return alert("Data peserta didik tidak ditemukan pada akun ini.");await deleteDoc(ref);writeCache(readCache().filter(x=>x.id!==id));if(idInput()?.value===id)kosongkan();alert("Data peserta didik berhasil dihapus.");refresh()}catch(e){alert("Gagal menghapus data peserta didik.\n\n"+(e.message||e))}};
document.addEventListener("click",e=>{const b=e.target.closest("#btnSimpanSantri,button[onclick*='simpanSantri']");if(b){e.preventDefault();e.stopImmediatePropagation();window.simpanSantri();return}const a=e.target.closest("[data-santri-action]");if(!a)return;e.preventDefault();e.stopPropagation();a.dataset.santriAction==="edit"?window.editSantri(a.dataset.id):window.hapusSantri(a.dataset.id)},true);
window.addEventListener("logoDashboardChanged",muatLogo);window.addEventListener("accountSettingsReady",muatLogo);document.addEventListener("DOMContentLoaded",muatLogo);import("./js/import-santri-ui.js").catch(()=>{});onAuthStateChanged(auth,u=>{userAktif=u||null;load()});
